// Code generated by protoc-gen-go.
// source: AuthC2SProtocol.proto
// DO NOT EDIT!

package Auth_C2S

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LoginInfo struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Passworld        *string `protobuf:"bytes,2,req" json:"Passworld,omitempty"`
	ClientType       *int32  `protobuf:"varint,3,req" json:"ClientType,omitempty"`
	MachineId        *string `protobuf:"bytes,4,req" json:"MachineId,omitempty"`
	SoftwareVersion  *int32  `protobuf:"varint,5,req" json:"SoftwareVersion,omitempty"`
	Status           *int32  `protobuf:"varint,6,opt" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LoginInfo) Reset()         { *this = LoginInfo{} }
func (this *LoginInfo) String() string { return proto.CompactTextString(this) }
func (*LoginInfo) ProtoMessage()       {}

func (this *LoginInfo) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *LoginInfo) GetPassworld() string {
	if this != nil && this.Passworld != nil {
		return *this.Passworld
	}
	return ""
}

func (this *LoginInfo) GetClientType() int32 {
	if this != nil && this.ClientType != nil {
		return *this.ClientType
	}
	return 0
}

func (this *LoginInfo) GetMachineId() string {
	if this != nil && this.MachineId != nil {
		return *this.MachineId
	}
	return ""
}

func (this *LoginInfo) GetSoftwareVersion() int32 {
	if this != nil && this.SoftwareVersion != nil {
		return *this.SoftwareVersion
	}
	return 0
}

func (this *LoginInfo) GetStatus() int32 {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

type HelloInfo struct {
	ClientType       *int32  `protobuf:"varint,1,req" json:"ClientType,omitempty"`
	Version          *uint32 `protobuf:"varint,2,req" json:"Version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *HelloInfo) Reset()         { *this = HelloInfo{} }
func (this *HelloInfo) String() string { return proto.CompactTextString(this) }
func (*HelloInfo) ProtoMessage()       {}

func (this *HelloInfo) GetClientType() int32 {
	if this != nil && this.ClientType != nil {
		return *this.ClientType
	}
	return 0
}

func (this *HelloInfo) GetVersion() uint32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type OAuthLogin struct {
	OAuthInfo        []byte  `protobuf:"bytes,1,req" json:"OAuthInfo,omitempty"`
	ClientType       *int32  `protobuf:"varint,4,req" json:"ClientType,omitempty"`
	MachineId        *string `protobuf:"bytes,5,req" json:"MachineId,omitempty"`
	SoftwareVersion  *int32  `protobuf:"varint,6,req" json:"SoftwareVersion,omitempty"`
	Status           *int32  `protobuf:"varint,7,opt" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *OAuthLogin) Reset()         { *this = OAuthLogin{} }
func (this *OAuthLogin) String() string { return proto.CompactTextString(this) }
func (*OAuthLogin) ProtoMessage()       {}

func (this *OAuthLogin) GetOAuthInfo() []byte {
	if this != nil {
		return this.OAuthInfo
	}
	return nil
}

func (this *OAuthLogin) GetClientType() int32 {
	if this != nil && this.ClientType != nil {
		return *this.ClientType
	}
	return 0
}

func (this *OAuthLogin) GetMachineId() string {
	if this != nil && this.MachineId != nil {
		return *this.MachineId
	}
	return ""
}

func (this *OAuthLogin) GetSoftwareVersion() int32 {
	if this != nil && this.SoftwareVersion != nil {
		return *this.SoftwareVersion
	}
	return 0
}

func (this *OAuthLogin) GetStatus() int32 {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

type OAuthRawInfo struct {
	Provider         *string `protobuf:"bytes,1,req" json:"Provider,omitempty"`
	Account          *string `protobuf:"bytes,2,req" json:"Account,omitempty"`
	Content          []byte  `protobuf:"bytes,3,opt" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *OAuthRawInfo) Reset()         { *this = OAuthRawInfo{} }
func (this *OAuthRawInfo) String() string { return proto.CompactTextString(this) }
func (*OAuthRawInfo) ProtoMessage()       {}

func (this *OAuthRawInfo) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return ""
}

func (this *OAuthRawInfo) GetAccount() string {
	if this != nil && this.Account != nil {
		return *this.Account
	}
	return ""
}

func (this *OAuthRawInfo) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func init() {
}
