// Code generated by protoc-gen-go.
// source: CommonBuddyProtocol.proto
// DO NOT EDIT!

package Auth_Buddy_Common

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RemoteUserAction int32

const (
	RemoteUserAction_INVITE_TO_CHANNEL         RemoteUserAction = 1
	RemoteUserAction_INVITE_TO_CHANNEL_IN_GAME RemoteUserAction = 2
)

var RemoteUserAction_name = map[int32]string{
	1: "INVITE_TO_CHANNEL",
	2: "INVITE_TO_CHANNEL_IN_GAME",
}
var RemoteUserAction_value = map[string]int32{
	"INVITE_TO_CHANNEL":         1,
	"INVITE_TO_CHANNEL_IN_GAME": 2,
}

func (x RemoteUserAction) Enum() *RemoteUserAction {
	p := new(RemoteUserAction)
	*p = x
	return p
}
func (x RemoteUserAction) String() string {
	return proto.EnumName(RemoteUserAction_name, int32(x))
}
func (x RemoteUserAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RemoteUserAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RemoteUserAction_value, data, "RemoteUserAction")
	if err != nil {
		return err
	}
	*x = RemoteUserAction(value)
	return nil
}

type RequestBuddyInfoType int32

const (
	RequestBuddyInfoType_BASIC_INFO    RequestBuddyInfoType = 1
	RequestBuddyInfoType_USER_INFO     RequestBuddyInfoType = 2
	RequestBuddyInfoType_STATUS_INFO   RequestBuddyInfoType = 4
	RequestBuddyInfoType_RELATION_INFO RequestBuddyInfoType = 8
	RequestBuddyInfoType_ALL_INFO      RequestBuddyInfoType = 268435455
)

var RequestBuddyInfoType_name = map[int32]string{
	1:         "BASIC_INFO",
	2:         "USER_INFO",
	4:         "STATUS_INFO",
	8:         "RELATION_INFO",
	268435455: "ALL_INFO",
}
var RequestBuddyInfoType_value = map[string]int32{
	"BASIC_INFO":    1,
	"USER_INFO":     2,
	"STATUS_INFO":   4,
	"RELATION_INFO": 8,
	"ALL_INFO":      268435455,
}

func (x RequestBuddyInfoType) Enum() *RequestBuddyInfoType {
	p := new(RequestBuddyInfoType)
	*p = x
	return p
}
func (x RequestBuddyInfoType) String() string {
	return proto.EnumName(RequestBuddyInfoType_name, int32(x))
}
func (x RequestBuddyInfoType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RequestBuddyInfoType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestBuddyInfoType_value, data, "RequestBuddyInfoType")
	if err != nil {
		return err
	}
	*x = RequestBuddyInfoType(value)
	return nil
}

type UserOnlineStatus int32

const (
	UserOnlineStatus_OFFLINE UserOnlineStatus = 0
	UserOnlineStatus_ONLINE  UserOnlineStatus = 1
	UserOnlineStatus_BUSY    UserOnlineStatus = 2
	UserOnlineStatus_GAMING  UserOnlineStatus = 3
	UserOnlineStatus_AWAY    UserOnlineStatus = 4
	UserOnlineStatus_HIDDEN  UserOnlineStatus = 5
)

var UserOnlineStatus_name = map[int32]string{
	0: "OFFLINE",
	1: "ONLINE",
	2: "BUSY",
	3: "GAMING",
	4: "AWAY",
	5: "HIDDEN",
}
var UserOnlineStatus_value = map[string]int32{
	"OFFLINE": 0,
	"ONLINE":  1,
	"BUSY":    2,
	"GAMING":  3,
	"AWAY":    4,
	"HIDDEN":  5,
}

func (x UserOnlineStatus) Enum() *UserOnlineStatus {
	p := new(UserOnlineStatus)
	*p = x
	return p
}
func (x UserOnlineStatus) String() string {
	return proto.EnumName(UserOnlineStatus_name, int32(x))
}
func (x UserOnlineStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UserOnlineStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserOnlineStatus_value, data, "UserOnlineStatus")
	if err != nil {
		return err
	}
	*x = UserOnlineStatus(value)
	return nil
}

type UserBuddyRelationship int32

const (
	UserBuddyRelationship_NONE    UserBuddyRelationship = 0
	UserBuddyRelationship_BUDDY   UserBuddyRelationship = 1
	UserBuddyRelationship_BLOCKBY UserBuddyRelationship = 2
)

var UserBuddyRelationship_name = map[int32]string{
	0: "NONE",
	1: "BUDDY",
	2: "BLOCKBY",
}
var UserBuddyRelationship_value = map[string]int32{
	"NONE":    0,
	"BUDDY":   1,
	"BLOCKBY": 2,
}

func (x UserBuddyRelationship) Enum() *UserBuddyRelationship {
	p := new(UserBuddyRelationship)
	*p = x
	return p
}
func (x UserBuddyRelationship) String() string {
	return proto.EnumName(UserBuddyRelationship_name, int32(x))
}
func (x UserBuddyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UserBuddyRelationship) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserBuddyRelationship_value, data, "UserBuddyRelationship")
	if err != nil {
		return err
	}
	*x = UserBuddyRelationship(value)
	return nil
}

type UserOptionInfo int32

const (
	UserOptionInfo_DISALLOW_STRANGER_CHAT UserOptionInfo = 1
)

var UserOptionInfo_name = map[int32]string{
	1: "DISALLOW_STRANGER_CHAT",
}
var UserOptionInfo_value = map[string]int32{
	"DISALLOW_STRANGER_CHAT": 1,
}

func (x UserOptionInfo) Enum() *UserOptionInfo {
	p := new(UserOptionInfo)
	*p = x
	return p
}
func (x UserOptionInfo) String() string {
	return proto.EnumName(UserOptionInfo_name, int32(x))
}
func (x UserOptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UserOptionInfo) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserOptionInfo_value, data, "UserOptionInfo")
	if err != nil {
		return err
	}
	*x = UserOptionInfo(value)
	return nil
}

type AddBuddyResultCode int32

const (
	AddBuddyResultCode_ACCEPT   AddBuddyResultCode = 1
	AddBuddyResultCode_REJECT   AddBuddyResultCode = 2
	AddBuddyResultCode_BOTH_ADD AddBuddyResultCode = 3
)

var AddBuddyResultCode_name = map[int32]string{
	1: "ACCEPT",
	2: "REJECT",
	3: "BOTH_ADD",
}
var AddBuddyResultCode_value = map[string]int32{
	"ACCEPT":   1,
	"REJECT":   2,
	"BOTH_ADD": 3,
}

func (x AddBuddyResultCode) Enum() *AddBuddyResultCode {
	p := new(AddBuddyResultCode)
	*p = x
	return p
}
func (x AddBuddyResultCode) String() string {
	return proto.EnumName(AddBuddyResultCode_name, int32(x))
}
func (x AddBuddyResultCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *AddBuddyResultCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AddBuddyResultCode_value, data, "AddBuddyResultCode")
	if err != nil {
		return err
	}
	*x = AddBuddyResultCode(value)
	return nil
}

type MetaInfoList struct {
	Media            []*MetaInfoList_MetaInfo `protobuf:"bytes,1,rep" json:"Media,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (this *MetaInfoList) Reset()         { *this = MetaInfoList{} }
func (this *MetaInfoList) String() string { return proto.CompactTextString(this) }
func (*MetaInfoList) ProtoMessage()       {}

type MetaInfoList_MetaInfo struct {
	MetaType         *string `protobuf:"bytes,1,req" json:"MetaType,omitempty"`
	Content          []byte  `protobuf:"bytes,2,req" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *MetaInfoList_MetaInfo) Reset()         { *this = MetaInfoList_MetaInfo{} }
func (this *MetaInfoList_MetaInfo) String() string { return proto.CompactTextString(this) }
func (*MetaInfoList_MetaInfo) ProtoMessage()       {}

func (this *MetaInfoList_MetaInfo) GetMetaType() string {
	if this != nil && this.MetaType != nil {
		return *this.MetaType
	}
	return ""
}

func (this *MetaInfoList_MetaInfo) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type TcpKeepAliveInfo struct {
	UserId           *int32  `protobuf:"varint,1,opt" json:"UserId,omitempty"`
	Token            *string `protobuf:"bytes,2,opt" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *TcpKeepAliveInfo) Reset()         { *this = TcpKeepAliveInfo{} }
func (this *TcpKeepAliveInfo) String() string { return proto.CompactTextString(this) }
func (*TcpKeepAliveInfo) ProtoMessage()       {}

func (this *TcpKeepAliveInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *TcpKeepAliveInfo) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type DynamicModuleList struct {
	Module           []*DynamicModuleList_DynamicModule `protobuf:"bytes,1,rep" json:"Module,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (this *DynamicModuleList) Reset()         { *this = DynamicModuleList{} }
func (this *DynamicModuleList) String() string { return proto.CompactTextString(this) }
func (*DynamicModuleList) ProtoMessage()       {}

type DynamicModuleList_DynamicModule struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Token            *string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DynamicModuleList_DynamicModule) Reset()         { *this = DynamicModuleList_DynamicModule{} }
func (this *DynamicModuleList_DynamicModule) String() string { return proto.CompactTextString(this) }
func (*DynamicModuleList_DynamicModule) ProtoMessage()       {}

func (this *DynamicModuleList_DynamicModule) GetUrl() string {
	if this != nil && this.Url != nil {
		return *this.Url
	}
	return ""
}

func (this *DynamicModuleList_DynamicModule) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type MultiFormatChatItem struct {
	Format           *string `protobuf:"bytes,1,opt" json:"Format,omitempty"`
	Content          []byte  `protobuf:"bytes,2,req" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *MultiFormatChatItem) Reset()         { *this = MultiFormatChatItem{} }
func (this *MultiFormatChatItem) String() string { return proto.CompactTextString(this) }
func (*MultiFormatChatItem) ProtoMessage()       {}

func (this *MultiFormatChatItem) GetFormat() string {
	if this != nil && this.Format != nil {
		return *this.Format
	}
	return ""
}

func (this *MultiFormatChatItem) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type MultiFormatChatList struct {
	ChatItems        []*MultiFormatChatItem `protobuf:"bytes,1,rep" json:"ChatItems,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (this *MultiFormatChatList) Reset()         { *this = MultiFormatChatList{} }
func (this *MultiFormatChatList) String() string { return proto.CompactTextString(this) }
func (*MultiFormatChatList) ProtoMessage()       {}

type BuddyCurrChannelTag struct {
	ChannelId        *int32  `protobuf:"varint,1,req" json:"ChannelId,omitempty"`
	SubChannelId     *int32  `protobuf:"varint,2,req" json:"SubChannelId,omitempty"`
	DisplayName      *string `protobuf:"bytes,3,opt" json:"DisplayName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BuddyCurrChannelTag) Reset()         { *this = BuddyCurrChannelTag{} }
func (this *BuddyCurrChannelTag) String() string { return proto.CompactTextString(this) }
func (*BuddyCurrChannelTag) ProtoMessage()       {}

func (this *BuddyCurrChannelTag) GetChannelId() int32 {
	if this != nil && this.ChannelId != nil {
		return *this.ChannelId
	}
	return 0
}

func (this *BuddyCurrChannelTag) GetSubChannelId() int32 {
	if this != nil && this.SubChannelId != nil {
		return *this.SubChannelId
	}
	return 0
}

func (this *BuddyCurrChannelTag) GetDisplayName() string {
	if this != nil && this.DisplayName != nil {
		return *this.DisplayName
	}
	return ""
}

type RemoteInviteChannelAction struct {
	ChannelId        *int32  `protobuf:"varint,1,req" json:"ChannelId,omitempty"`
	SubChannelId     *int32  `protobuf:"varint,2,req" json:"SubChannelId,omitempty"`
	Message          *string `protobuf:"bytes,3,opt" json:"Message,omitempty"`
	Param            []byte  `protobuf:"bytes,4,opt" json:"Param,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteInviteChannelAction) Reset()         { *this = RemoteInviteChannelAction{} }
func (this *RemoteInviteChannelAction) String() string { return proto.CompactTextString(this) }
func (*RemoteInviteChannelAction) ProtoMessage()       {}

func (this *RemoteInviteChannelAction) GetChannelId() int32 {
	if this != nil && this.ChannelId != nil {
		return *this.ChannelId
	}
	return 0
}

func (this *RemoteInviteChannelAction) GetSubChannelId() int32 {
	if this != nil && this.SubChannelId != nil {
		return *this.SubChannelId
	}
	return 0
}

func (this *RemoteInviteChannelAction) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

func (this *RemoteInviteChannelAction) GetParam() []byte {
	if this != nil {
		return this.Param
	}
	return nil
}

func init() {
	proto.RegisterEnum("Auth.Buddy.Common.RemoteUserAction", RemoteUserAction_name, RemoteUserAction_value)
	proto.RegisterEnum("Auth.Buddy.Common.RequestBuddyInfoType", RequestBuddyInfoType_name, RequestBuddyInfoType_value)
	proto.RegisterEnum("Auth.Buddy.Common.UserOnlineStatus", UserOnlineStatus_name, UserOnlineStatus_value)
	proto.RegisterEnum("Auth.Buddy.Common.UserBuddyRelationship", UserBuddyRelationship_name, UserBuddyRelationship_value)
	proto.RegisterEnum("Auth.Buddy.Common.UserOptionInfo", UserOptionInfo_name, UserOptionInfo_value)
	proto.RegisterEnum("Auth.Buddy.Common.AddBuddyResultCode", AddBuddyResultCode_name, AddBuddyResultCode_value)
}
