// Code generated by protoc-gen-go.
// source: S2CDiscussion.proto
// DO NOT EDIT!

package Discussion_S2C

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type DiscussionInfo struct {
	DiscussionId     *int64  `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Title            *string `protobuf:"bytes,2,req" json:"Title,omitempty"`
	Kind             *int32  `protobuf:"varint,3,opt" json:"Kind,omitempty"`
	Option           *int32  `protobuf:"varint,4,opt" json:"Option,omitempty"`
	Icon             *int64  `protobuf:"varint,5,opt" json:"Icon,omitempty"`
	Version          *int32  `protobuf:"varint,6,req" json:"Version,omitempty"`
	MemberVersion    *int32  `protobuf:"varint,7,opt" json:"MemberVersion,omitempty"`
	CreateDate       *int32  `protobuf:"varint,8,opt" json:"CreateDate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DiscussionInfo) Reset()         { *this = DiscussionInfo{} }
func (this *DiscussionInfo) String() string { return proto.CompactTextString(this) }
func (*DiscussionInfo) ProtoMessage()       {}

func (this *DiscussionInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *DiscussionInfo) GetTitle() string {
	if this != nil && this.Title != nil {
		return *this.Title
	}
	return ""
}

func (this *DiscussionInfo) GetKind() int32 {
	if this != nil && this.Kind != nil {
		return *this.Kind
	}
	return 0
}

func (this *DiscussionInfo) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

func (this *DiscussionInfo) GetIcon() int64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

func (this *DiscussionInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *DiscussionInfo) GetMemberVersion() int32 {
	if this != nil && this.MemberVersion != nil {
		return *this.MemberVersion
	}
	return 0
}

func (this *DiscussionInfo) GetCreateDate() int32 {
	if this != nil && this.CreateDate != nil {
		return *this.CreateDate
	}
	return 0
}

type MyDiscussionOption struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Option           *int32 `protobuf:"varint,2,opt" json:"Option,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *MyDiscussionOption) Reset()         { *this = MyDiscussionOption{} }
func (this *MyDiscussionOption) String() string { return proto.CompactTextString(this) }
func (*MyDiscussionOption) ProtoMessage()       {}

func (this *MyDiscussionOption) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *MyDiscussionOption) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

type UserDiscussionList struct {
	Discussion       []*UserDiscussionList_DiscussionSimpleInfo `protobuf:"bytes,1,rep" json:"Discussion,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (this *UserDiscussionList) Reset()         { *this = UserDiscussionList{} }
func (this *UserDiscussionList) String() string { return proto.CompactTextString(this) }
func (*UserDiscussionList) ProtoMessage()       {}

type UserDiscussionList_DiscussionSimpleInfo struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Version          *int32 `protobuf:"varint,2,opt" json:"Version,omitempty"`
	MemberVersion    *int32 `protobuf:"varint,3,opt" json:"MemberVersion,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *UserDiscussionList_DiscussionSimpleInfo) Reset() {
	*this = UserDiscussionList_DiscussionSimpleInfo{}
}
func (this *UserDiscussionList_DiscussionSimpleInfo) String() string {
	return proto.CompactTextString(this)
}
func (*UserDiscussionList_DiscussionSimpleInfo) ProtoMessage() {}

func (this *UserDiscussionList_DiscussionSimpleInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *UserDiscussionList_DiscussionSimpleInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *UserDiscussionList_DiscussionSimpleInfo) GetMemberVersion() int32 {
	if this != nil && this.MemberVersion != nil {
		return *this.MemberVersion
	}
	return 0
}

type DiscussionMemberInfo struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Position         *int32 `protobuf:"varint,2,opt" json:"Position,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *DiscussionMemberInfo) Reset()         { *this = DiscussionMemberInfo{} }
func (this *DiscussionMemberInfo) String() string { return proto.CompactTextString(this) }
func (*DiscussionMemberInfo) ProtoMessage()       {}

func (this *DiscussionMemberInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *DiscussionMemberInfo) GetPosition() int32 {
	if this != nil && this.Position != nil {
		return *this.Position
	}
	return 0
}

type DiscussionMemberList struct {
	DiscussionId     *int64                  `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Member           []*DiscussionMemberInfo `protobuf:"bytes,2,rep" json:"Member,omitempty"`
	MemberVersion    *int32                  `protobuf:"varint,3,opt" json:"MemberVersion,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (this *DiscussionMemberList) Reset()         { *this = DiscussionMemberList{} }
func (this *DiscussionMemberList) String() string { return proto.CompactTextString(this) }
func (*DiscussionMemberList) ProtoMessage()       {}

func (this *DiscussionMemberList) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *DiscussionMemberList) GetMemberVersion() int32 {
	if this != nil && this.MemberVersion != nil {
		return *this.MemberVersion
	}
	return 0
}

type DiscussionError struct {
	DiscussionId     *int64 `protobuf:"varint,1,opt" json:"DiscussionId,omitempty"`
	ErrorCode        *int32 `protobuf:"varint,2,req" json:"ErrorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *DiscussionError) Reset()         { *this = DiscussionError{} }
func (this *DiscussionError) String() string { return proto.CompactTextString(this) }
func (*DiscussionError) ProtoMessage()       {}

func (this *DiscussionError) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *DiscussionError) GetErrorCode() int32 {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

type NewDiscussionArrival struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *NewDiscussionArrival) Reset()         { *this = NewDiscussionArrival{} }
func (this *NewDiscussionArrival) String() string { return proto.CompactTextString(this) }
func (*NewDiscussionArrival) ProtoMessage()       {}

func (this *NewDiscussionArrival) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

type MemberLeave struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	UserId           *int32 `protobuf:"varint,2,req" json:"UserId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *MemberLeave) Reset()         { *this = MemberLeave{} }
func (this *MemberLeave) String() string { return proto.CompactTextString(this) }
func (*MemberLeave) ProtoMessage()       {}

func (this *MemberLeave) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *MemberLeave) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type MemberJoin struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	UserId           *int32 `protobuf:"varint,2,req" json:"UserId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *MemberJoin) Reset()         { *this = MemberJoin{} }
func (this *MemberJoin) String() string { return proto.CompactTextString(this) }
func (*MemberJoin) ProtoMessage()       {}

func (this *MemberJoin) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *MemberJoin) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type ChatInfo struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	UserId           *int32 `protobuf:"varint,2,req" json:"UserId,omitempty"`
	Content          []byte `protobuf:"bytes,3,req" json:"Content,omitempty"`
	TimeStamp        *int32 `protobuf:"varint,4,opt" json:"TimeStamp,omitempty"`
	MsgId            *int64 `protobuf:"varint,5,opt" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatInfo) Reset()         { *this = ChatInfo{} }
func (this *ChatInfo) String() string { return proto.CompactTextString(this) }
func (*ChatInfo) ProtoMessage()       {}

func (this *ChatInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *ChatInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatInfo) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *ChatInfo) GetTimeStamp() int32 {
	if this != nil && this.TimeStamp != nil {
		return *this.TimeStamp
	}
	return 0
}

func (this *ChatInfo) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type ChatInfoAck struct {
	MsgId            *int64 `protobuf:"varint,1,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatInfoAck) Reset()         { *this = ChatInfoAck{} }
func (this *ChatInfoAck) String() string { return proto.CompactTextString(this) }
func (*ChatInfoAck) ProtoMessage()       {}

func (this *ChatInfoAck) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type InviteMember struct {
	DiscussionId     *int64  `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	FromId           *int32  `protobuf:"varint,2,req" json:"FromId,omitempty"`
	Memo             *string `protobuf:"bytes,3,opt" json:"Memo,omitempty"`
	InviteId         []byte  `protobuf:"bytes,4,req" json:"InviteId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InviteMember) Reset()         { *this = InviteMember{} }
func (this *InviteMember) String() string { return proto.CompactTextString(this) }
func (*InviteMember) ProtoMessage()       {}

func (this *InviteMember) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *InviteMember) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *InviteMember) GetMemo() string {
	if this != nil && this.Memo != nil {
		return *this.Memo
	}
	return ""
}

func (this *InviteMember) GetInviteId() []byte {
	if this != nil {
		return this.InviteId
	}
	return nil
}

func init() {
}
