// Code generated by protoc-gen-go.
// source: C2SDiscussion.proto
// DO NOT EDIT!

package Discussion_C2S

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CreateDiscussion struct {
	DiscussionId     *int64  `protobuf:"varint,1,opt" json:"DiscussionId,omitempty"`
	Title            *string `protobuf:"bytes,2,req" json:"Title,omitempty"`
	Icon             *int64  `protobuf:"varint,3,opt" json:"Icon,omitempty"`
	InviteList       []int32 `protobuf:"varint,4,rep" json:"InviteList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateDiscussion) Reset()         { *this = CreateDiscussion{} }
func (this *CreateDiscussion) String() string { return proto.CompactTextString(this) }
func (*CreateDiscussion) ProtoMessage()       {}

func (this *CreateDiscussion) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *CreateDiscussion) GetTitle() string {
	if this != nil && this.Title != nil {
		return *this.Title
	}
	return ""
}

func (this *CreateDiscussion) GetIcon() int64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

type InviteMember struct {
	DiscussionId     *int64  `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Members          []int32 `protobuf:"varint,2,rep" json:"Members,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *InviteMember) Reset()         { *this = InviteMember{} }
func (this *InviteMember) String() string { return proto.CompactTextString(this) }
func (*InviteMember) ProtoMessage()       {}

func (this *InviteMember) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

type InviteMemberResult struct {
	InviteId         []byte `protobuf:"bytes,1,req" json:"InviteId,omitempty"`
	Agree            *int32 `protobuf:"varint,2,req" json:"Agree,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *InviteMemberResult) Reset()         { *this = InviteMemberResult{} }
func (this *InviteMemberResult) String() string { return proto.CompactTextString(this) }
func (*InviteMemberResult) ProtoMessage()       {}

func (this *InviteMemberResult) GetInviteId() []byte {
	if this != nil {
		return this.InviteId
	}
	return nil
}

func (this *InviteMemberResult) GetAgree() int32 {
	if this != nil && this.Agree != nil {
		return *this.Agree
	}
	return 0
}

type LeaveDiscussion struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *LeaveDiscussion) Reset()         { *this = LeaveDiscussion{} }
func (this *LeaveDiscussion) String() string { return proto.CompactTextString(this) }
func (*LeaveDiscussion) ProtoMessage()       {}

func (this *LeaveDiscussion) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

type ChatInfo struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Content          []byte `protobuf:"bytes,2,req" json:"Content,omitempty"`
	MsgId            *int64 `protobuf:"varint,3,opt" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatInfo) Reset()         { *this = ChatInfo{} }
func (this *ChatInfo) String() string { return proto.CompactTextString(this) }
func (*ChatInfo) ProtoMessage()       {}

func (this *ChatInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *ChatInfo) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *ChatInfo) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type ChatInfoRecvedAck struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	MsgId            *int64 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatInfoRecvedAck) Reset()         { *this = ChatInfoRecvedAck{} }
func (this *ChatInfoRecvedAck) String() string { return proto.CompactTextString(this) }
func (*ChatInfoRecvedAck) ProtoMessage()       {}

func (this *ChatInfoRecvedAck) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *ChatInfoRecvedAck) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type ChangeMyOption struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Option           *int32 `protobuf:"varint,2,opt" json:"Option,omitempty"`
	RequestId        []byte `protobuf:"bytes,3,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChangeMyOption) Reset()         { *this = ChangeMyOption{} }
func (this *ChangeMyOption) String() string { return proto.CompactTextString(this) }
func (*ChangeMyOption) ProtoMessage()       {}

func (this *ChangeMyOption) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *ChangeMyOption) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

func (this *ChangeMyOption) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type ChangeDiscussionInfo struct {
	DiscussionId     *int64  `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Option           *int32  `protobuf:"varint,2,opt" json:"Option,omitempty"`
	Title            *string `protobuf:"bytes,3,opt" json:"Title,omitempty"`
	Icon             *int64  `protobuf:"varint,4,opt" json:"Icon,omitempty"`
	RequestId        []byte  `protobuf:"bytes,5,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeDiscussionInfo) Reset()         { *this = ChangeDiscussionInfo{} }
func (this *ChangeDiscussionInfo) String() string { return proto.CompactTextString(this) }
func (*ChangeDiscussionInfo) ProtoMessage()       {}

func (this *ChangeDiscussionInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *ChangeDiscussionInfo) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

func (this *ChangeDiscussionInfo) GetTitle() string {
	if this != nil && this.Title != nil {
		return *this.Title
	}
	return ""
}

func (this *ChangeDiscussionInfo) GetIcon() int64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

func (this *ChangeDiscussionInfo) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestDiscussionInfo struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	Version          *int32 `protobuf:"varint,2,opt" json:"Version,omitempty"`
	MemberVersion    *int32 `protobuf:"varint,3,opt" json:"MemberVersion,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestDiscussionInfo) Reset()         { *this = RequestDiscussionInfo{} }
func (this *RequestDiscussionInfo) String() string { return proto.CompactTextString(this) }
func (*RequestDiscussionInfo) ProtoMessage()       {}

func (this *RequestDiscussionInfo) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *RequestDiscussionInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *RequestDiscussionInfo) GetMemberVersion() int32 {
	if this != nil && this.MemberVersion != nil {
		return *this.MemberVersion
	}
	return 0
}

type RequestMyDiscussion struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestMyDiscussion) Reset()         { *this = RequestMyDiscussion{} }
func (this *RequestMyDiscussion) String() string { return proto.CompactTextString(this) }
func (*RequestMyDiscussion) ProtoMessage()       {}

type SubscribeDiscussionChanged struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	EventCode        *int32 `protobuf:"varint,2,req" json:"EventCode,omitempty"`
	Version          *int32 `protobuf:"varint,3,opt" json:"Version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *SubscribeDiscussionChanged) Reset()         { *this = SubscribeDiscussionChanged{} }
func (this *SubscribeDiscussionChanged) String() string { return proto.CompactTextString(this) }
func (*SubscribeDiscussionChanged) ProtoMessage()       {}

func (this *SubscribeDiscussionChanged) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *SubscribeDiscussionChanged) GetEventCode() int32 {
	if this != nil && this.EventCode != nil {
		return *this.EventCode
	}
	return 0
}

func (this *SubscribeDiscussionChanged) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type UnsubscribeDiscussionChanged struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	EventCode        *int32 `protobuf:"varint,2,req" json:"EventCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *UnsubscribeDiscussionChanged) Reset()         { *this = UnsubscribeDiscussionChanged{} }
func (this *UnsubscribeDiscussionChanged) String() string { return proto.CompactTextString(this) }
func (*UnsubscribeDiscussionChanged) ProtoMessage()       {}

func (this *UnsubscribeDiscussionChanged) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func (this *UnsubscribeDiscussionChanged) GetEventCode() int32 {
	if this != nil && this.EventCode != nil {
		return *this.EventCode
	}
	return 0
}

type RequestMyOption struct {
	DiscussionId     *int64 `protobuf:"varint,1,req" json:"DiscussionId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestMyOption) Reset()         { *this = RequestMyOption{} }
func (this *RequestMyOption) String() string { return proto.CompactTextString(this) }
func (*RequestMyOption) ProtoMessage()       {}

func (this *RequestMyOption) GetDiscussionId() int64 {
	if this != nil && this.DiscussionId != nil {
		return *this.DiscussionId
	}
	return 0
}

func init() {
}
