// Code generated by protoc-gen-go.
// source: SimpleTokenProtocol.proto
// DO NOT EDIT!

package TOKEN_S

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type UserInfo struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	Level            *int32  `protobuf:"varint,3,opt" json:"Level,omitempty"`
	UserType         *int32  `protobuf:"varint,4,opt" json:"UserType,omitempty"`
	ClientType       *int32  `protobuf:"varint,5,opt" json:"ClientType,omitempty"`
	Status           *int32  `protobuf:"varint,6,opt" json:"Status,omitempty"`
	Icon             *uint64 `protobuf:"varint,7,req" json:"Icon,omitempty"`
	NickName         *string `protobuf:"bytes,8,opt" json:"NickName,omitempty"`
	Gender           *int32  `protobuf:"varint,9,opt" json:"Gender,omitempty"`
	Birthday         *int32  `protobuf:"varint,10,opt" json:"Birthday,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *UserInfo) Reset()         { *this = UserInfo{} }
func (this *UserInfo) String() string { return proto.CompactTextString(this) }
func (*UserInfo) ProtoMessage()       {}

func (this *UserInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *UserInfo) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *UserInfo) GetLevel() int32 {
	if this != nil && this.Level != nil {
		return *this.Level
	}
	return 0
}

func (this *UserInfo) GetUserType() int32 {
	if this != nil && this.UserType != nil {
		return *this.UserType
	}
	return 0
}

func (this *UserInfo) GetClientType() int32 {
	if this != nil && this.ClientType != nil {
		return *this.ClientType
	}
	return 0
}

func (this *UserInfo) GetStatus() int32 {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

func (this *UserInfo) GetIcon() uint64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

func (this *UserInfo) GetNickName() string {
	if this != nil && this.NickName != nil {
		return *this.NickName
	}
	return ""
}

func (this *UserInfo) GetGender() int32 {
	if this != nil && this.Gender != nil {
		return *this.Gender
	}
	return 0
}

func (this *UserInfo) GetBirthday() int32 {
	if this != nil && this.Birthday != nil {
		return *this.Birthday
	}
	return 0
}

type RawLoginTokenInfo struct {
	User             *UserInfo `protobuf:"bytes,1,req" json:"User,omitempty"`
	ExpiredDate      *uint32   `protobuf:"varint,2,req" json:"ExpiredDate,omitempty"`
	IP               *uint32   `protobuf:"varint,3,req" json:"IP,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *RawLoginTokenInfo) Reset()         { *this = RawLoginTokenInfo{} }
func (this *RawLoginTokenInfo) String() string { return proto.CompactTextString(this) }
func (*RawLoginTokenInfo) ProtoMessage()       {}

func (this *RawLoginTokenInfo) GetUser() *UserInfo {
	if this != nil {
		return this.User
	}
	return nil
}

func (this *RawLoginTokenInfo) GetExpiredDate() uint32 {
	if this != nil && this.ExpiredDate != nil {
		return *this.ExpiredDate
	}
	return 0
}

func (this *RawLoginTokenInfo) GetIP() uint32 {
	if this != nil && this.IP != nil {
		return *this.IP
	}
	return 0
}

type P2PServerTokenInfo struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	ExpiredDate      *uint32 `protobuf:"varint,2,req" json:"ExpiredDate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *P2PServerTokenInfo) Reset()         { *this = P2PServerTokenInfo{} }
func (this *P2PServerTokenInfo) String() string { return proto.CompactTextString(this) }
func (*P2PServerTokenInfo) ProtoMessage()       {}

func (this *P2PServerTokenInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *P2PServerTokenInfo) GetExpiredDate() uint32 {
	if this != nil && this.ExpiredDate != nil {
		return *this.ExpiredDate
	}
	return 0
}

type RASATokenInfo struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	ExpiredDate      *uint32 `protobuf:"varint,3,req" json:"ExpiredDate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RASATokenInfo) Reset()         { *this = RASATokenInfo{} }
func (this *RASATokenInfo) String() string { return proto.CompactTextString(this) }
func (*RASATokenInfo) ProtoMessage()       {}

func (this *RASATokenInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RASATokenInfo) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *RASATokenInfo) GetExpiredDate() uint32 {
	if this != nil && this.ExpiredDate != nil {
		return *this.ExpiredDate
	}
	return 0
}

func init() {
}
