// Code generated by protoc-gen-go.
// source: FileServerProtocol.proto
// DO NOT EDIT!

package FSSystem

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MultiFileDataItemFormat struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Content          []byte  `protobuf:"bytes,2,opt" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *MultiFileDataItemFormat) Reset()         { *this = MultiFileDataItemFormat{} }
func (this *MultiFileDataItemFormat) String() string { return proto.CompactTextString(this) }
func (*MultiFileDataItemFormat) ProtoMessage()       {}

func (this *MultiFileDataItemFormat) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *MultiFileDataItemFormat) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type MultiFileDataFormat struct {
	Files            []*MultiFileDataItemFormat `protobuf:"bytes,1,rep" json:"Files,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (this *MultiFileDataFormat) Reset()         { *this = MultiFileDataFormat{} }
func (this *MultiFileDataFormat) String() string { return proto.CompactTextString(this) }
func (*MultiFileDataFormat) ProtoMessage()       {}

type ImageUploadRequest struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	Name             *string `protobuf:"bytes,2,opt" json:"Name,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req" json:"Content,omitempty"`
	Thumb            *bool   `protobuf:"varint,4,req" json:"Thumb,omitempty"`
	Type             *string `protobuf:"bytes,5,opt" json:"Type,omitempty"`
	Timeout          *int32  `protobuf:"varint,6,opt" json:"Timeout,omitempty"`
	RequestId        *string `protobuf:"bytes,7,opt" json:"RequestId,omitempty"`
	ResTag           *string `protobuf:"bytes,8,opt" json:"ResTag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadRequest) Reset()         { *this = ImageUploadRequest{} }
func (this *ImageUploadRequest) String() string { return proto.CompactTextString(this) }
func (*ImageUploadRequest) ProtoMessage()       {}

func (this *ImageUploadRequest) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *ImageUploadRequest) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *ImageUploadRequest) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *ImageUploadRequest) GetThumb() bool {
	if this != nil && this.Thumb != nil {
		return *this.Thumb
	}
	return false
}

func (this *ImageUploadRequest) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *ImageUploadRequest) GetTimeout() int32 {
	if this != nil && this.Timeout != nil {
		return *this.Timeout
	}
	return 0
}

func (this *ImageUploadRequest) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *ImageUploadRequest) GetResTag() string {
	if this != nil && this.ResTag != nil {
		return *this.ResTag
	}
	return ""
}

type ImageDownloadRequest struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	Thumb            *bool   `protobuf:"varint,3,opt" json:"Thumb,omitempty"`
	RequestId        *string `protobuf:"bytes,4,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageDownloadRequest) Reset()         { *this = ImageDownloadRequest{} }
func (this *ImageDownloadRequest) String() string { return proto.CompactTextString(this) }
func (*ImageDownloadRequest) ProtoMessage()       {}

func (this *ImageDownloadRequest) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *ImageDownloadRequest) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *ImageDownloadRequest) GetThumb() bool {
	if this != nil && this.Thumb != nil {
		return *this.Thumb
	}
	return false
}

func (this *ImageDownloadRequest) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type ImageUploadRequestHeader struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	Thumb            *bool   `protobuf:"varint,4,req" json:"Thumb,omitempty"`
	Type             *string `protobuf:"bytes,5,opt" json:"Type,omitempty"`
	Timeout          *int32  `protobuf:"varint,6,opt" json:"Timeout,omitempty"`
	RequestId        *string `protobuf:"bytes,7,req" json:"RequestId,omitempty"`
	ResTag           *string `protobuf:"bytes,8,opt" json:"ResTag,omitempty"`
	TotalBlock       *int32  `protobuf:"varint,9,req" json:"TotalBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadRequestHeader) Reset()         { *this = ImageUploadRequestHeader{} }
func (this *ImageUploadRequestHeader) String() string { return proto.CompactTextString(this) }
func (*ImageUploadRequestHeader) ProtoMessage()       {}

func (this *ImageUploadRequestHeader) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *ImageUploadRequestHeader) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *ImageUploadRequestHeader) GetThumb() bool {
	if this != nil && this.Thumb != nil {
		return *this.Thumb
	}
	return false
}

func (this *ImageUploadRequestHeader) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *ImageUploadRequestHeader) GetTimeout() int32 {
	if this != nil && this.Timeout != nil {
		return *this.Timeout
	}
	return 0
}

func (this *ImageUploadRequestHeader) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *ImageUploadRequestHeader) GetResTag() string {
	if this != nil && this.ResTag != nil {
		return *this.ResTag
	}
	return ""
}

func (this *ImageUploadRequestHeader) GetTotalBlock() int32 {
	if this != nil && this.TotalBlock != nil {
		return *this.TotalBlock
	}
	return 0
}

type ImageUploadRequestPart struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	PartId           *int32  `protobuf:"varint,2,req" json:"PartId,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadRequestPart) Reset()         { *this = ImageUploadRequestPart{} }
func (this *ImageUploadRequestPart) String() string { return proto.CompactTextString(this) }
func (*ImageUploadRequestPart) ProtoMessage()       {}

func (this *ImageUploadRequestPart) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *ImageUploadRequestPart) GetPartId() int32 {
	if this != nil && this.PartId != nil {
		return *this.PartId
	}
	return 0
}

func (this *ImageUploadRequestPart) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type BatchUploadRequestHeader struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	RequestId        *string `protobuf:"bytes,2,req" json:"RequestId,omitempty"`
	TotalBlock       *int32  `protobuf:"varint,3,req" json:"TotalBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BatchUploadRequestHeader) Reset()         { *this = BatchUploadRequestHeader{} }
func (this *BatchUploadRequestHeader) String() string { return proto.CompactTextString(this) }
func (*BatchUploadRequestHeader) ProtoMessage()       {}

func (this *BatchUploadRequestHeader) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *BatchUploadRequestHeader) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *BatchUploadRequestHeader) GetTotalBlock() int32 {
	if this != nil && this.TotalBlock != nil {
		return *this.TotalBlock
	}
	return 0
}

type BatchUploadRequestPart struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	PartId           *int32  `protobuf:"varint,2,req" json:"PartId,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BatchUploadRequestPart) Reset()         { *this = BatchUploadRequestPart{} }
func (this *BatchUploadRequestPart) String() string { return proto.CompactTextString(this) }
func (*BatchUploadRequestPart) ProtoMessage()       {}

func (this *BatchUploadRequestPart) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *BatchUploadRequestPart) GetPartId() int32 {
	if this != nil && this.PartId != nil {
		return *this.PartId
	}
	return 0
}

func (this *BatchUploadRequestPart) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type ImageUploadResult struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	RequestId        *string `protobuf:"bytes,2,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadResult) Reset()         { *this = ImageUploadResult{} }
func (this *ImageUploadResult) String() string { return proto.CompactTextString(this) }
func (*ImageUploadResult) ProtoMessage()       {}

func (this *ImageUploadResult) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *ImageUploadResult) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type FSGeneralError struct {
	ErrorCode        *int32  `protobuf:"varint,1,req" json:"ErrorCode,omitempty"`
	RequestId        *string `protobuf:"bytes,2,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *FSGeneralError) Reset()         { *this = FSGeneralError{} }
func (this *FSGeneralError) String() string { return proto.CompactTextString(this) }
func (*FSGeneralError) ProtoMessage()       {}

func (this *FSGeneralError) GetErrorCode() int32 {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

func (this *FSGeneralError) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type ImageDownloadResult struct {
	Content          []byte  `protobuf:"bytes,1,req" json:"Content,omitempty"`
	Thumb            *bool   `protobuf:"varint,2,opt" json:"Thumb,omitempty"`
	RequestId        *string `protobuf:"bytes,3,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageDownloadResult) Reset()         { *this = ImageDownloadResult{} }
func (this *ImageDownloadResult) String() string { return proto.CompactTextString(this) }
func (*ImageDownloadResult) ProtoMessage()       {}

func (this *ImageDownloadResult) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *ImageDownloadResult) GetThumb() bool {
	if this != nil && this.Thumb != nil {
		return *this.Thumb
	}
	return false
}

func (this *ImageDownloadResult) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type ImageUploadRequestPartAck struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	PartId           *int32  `protobuf:"varint,2,req" json:"PartId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadRequestPartAck) Reset()         { *this = ImageUploadRequestPartAck{} }
func (this *ImageUploadRequestPartAck) String() string { return proto.CompactTextString(this) }
func (*ImageUploadRequestPartAck) ProtoMessage()       {}

func (this *ImageUploadRequestPartAck) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *ImageUploadRequestPartAck) GetPartId() int32 {
	if this != nil && this.PartId != nil {
		return *this.PartId
	}
	return 0
}

type ImageUploadRequestHeaderAck struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	Exists           *bool   `protobuf:"varint,3,req" json:"Exists,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ImageUploadRequestHeaderAck) Reset()         { *this = ImageUploadRequestHeaderAck{} }
func (this *ImageUploadRequestHeaderAck) String() string { return proto.CompactTextString(this) }
func (*ImageUploadRequestHeaderAck) ProtoMessage()       {}

func (this *ImageUploadRequestHeaderAck) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *ImageUploadRequestHeaderAck) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *ImageUploadRequestHeaderAck) GetExists() bool {
	if this != nil && this.Exists != nil {
		return *this.Exists
	}
	return false
}

type BatchUploadRequestPartAck struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	PartId           *int32  `protobuf:"varint,2,req" json:"PartId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BatchUploadRequestPartAck) Reset()         { *this = BatchUploadRequestPartAck{} }
func (this *BatchUploadRequestPartAck) String() string { return proto.CompactTextString(this) }
func (*BatchUploadRequestPartAck) ProtoMessage()       {}

func (this *BatchUploadRequestPartAck) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *BatchUploadRequestPartAck) GetPartId() int32 {
	if this != nil && this.PartId != nil {
		return *this.PartId
	}
	return 0
}

type BatchUploadRequestHeaderAck struct {
	RequestId        *string `protobuf:"bytes,1,req" json:"RequestId,omitempty"`
	Exists           *bool   `protobuf:"varint,2,req" json:"Exists,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BatchUploadRequestHeaderAck) Reset()         { *this = BatchUploadRequestHeaderAck{} }
func (this *BatchUploadRequestHeaderAck) String() string { return proto.CompactTextString(this) }
func (*BatchUploadRequestHeaderAck) ProtoMessage()       {}

func (this *BatchUploadRequestHeaderAck) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func (this *BatchUploadRequestHeaderAck) GetExists() bool {
	if this != nil && this.Exists != nil {
		return *this.Exists
	}
	return false
}

type Parameter struct {
	Cs               *int64 `protobuf:"varint,1,req,name=cs" json:"cs,omitempty"`
	From             *int64 `protobuf:"varint,2,opt,name=from" json:"from,omitempty"`
	RequestId        []byte `protobuf:"bytes,3,opt,name=requestId" json:"requestId,omitempty"`
	Index            *int32 `protobuf:"varint,4,req,name=index" json:"index,omitempty"`
	Thumb            *bool  `protobuf:"varint,5,opt,name=thumb" json:"thumb,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Parameter) Reset()         { *this = Parameter{} }
func (this *Parameter) String() string { return proto.CompactTextString(this) }
func (*Parameter) ProtoMessage()       {}

func (this *Parameter) GetCs() int64 {
	if this != nil && this.Cs != nil {
		return *this.Cs
	}
	return 0
}

func (this *Parameter) GetFrom() int64 {
	if this != nil && this.From != nil {
		return *this.From
	}
	return 0
}

func (this *Parameter) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *Parameter) GetIndex() int32 {
	if this != nil && this.Index != nil {
		return *this.Index
	}
	return 0
}

func (this *Parameter) GetThumb() bool {
	if this != nil && this.Thumb != nil {
		return *this.Thumb
	}
	return false
}

type QueryFileExistence struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Token            []byte  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,req,name=parameter" json:"parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *QueryFileExistence) Reset()         { *this = QueryFileExistence{} }
func (this *QueryFileExistence) String() string { return proto.CompactTextString(this) }
func (*QueryFileExistence) ProtoMessage()       {}

func (this *QueryFileExistence) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *QueryFileExistence) GetToken() []byte {
	if this != nil {
		return this.Token
	}
	return nil
}

func (this *QueryFileExistence) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type FileExistenceResult struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Exist            *bool   `protobuf:"varint,2,req,name=exist" json:"exist,omitempty"`
	Token            []byte  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	Parameter        []byte  `protobuf:"bytes,4,req,name=parameter" json:"parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *FileExistenceResult) Reset()         { *this = FileExistenceResult{} }
func (this *FileExistenceResult) String() string { return proto.CompactTextString(this) }
func (*FileExistenceResult) ProtoMessage()       {}

func (this *FileExistenceResult) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *FileExistenceResult) GetExist() bool {
	if this != nil && this.Exist != nil {
		return *this.Exist
	}
	return false
}

func (this *FileExistenceResult) GetToken() []byte {
	if this != nil {
		return this.Token
	}
	return nil
}

func (this *FileExistenceResult) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type FileRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Token            []byte  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,req,name=parameter" json:"parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *FileRequest) Reset()         { *this = FileRequest{} }
func (this *FileRequest) String() string { return proto.CompactTextString(this) }
func (*FileRequest) ProtoMessage()       {}

func (this *FileRequest) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *FileRequest) GetToken() []byte {
	if this != nil {
		return this.Token
	}
	return nil
}

func (this *FileRequest) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type FileResponse struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Token            []byte  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Content          []byte  `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Parameter        []byte  `protobuf:"bytes,5,req,name=parameter" json:"parameter,omitempty"`
	Expire           *int32  `protobuf:"varint,6,opt,name=expire,def=24" json:"expire,omitempty"`
	ErrorCode        *int32  `protobuf:"varint,7,opt,name=error_code" json:"error_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *FileResponse) Reset()         { *this = FileResponse{} }
func (this *FileResponse) String() string { return proto.CompactTextString(this) }
func (*FileResponse) ProtoMessage()       {}

const Default_FileResponse_Expire int32 = 24

func (this *FileResponse) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *FileResponse) GetToken() []byte {
	if this != nil {
		return this.Token
	}
	return nil
}

func (this *FileResponse) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *FileResponse) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *FileResponse) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *FileResponse) GetExpire() int32 {
	if this != nil && this.Expire != nil {
		return *this.Expire
	}
	return Default_FileResponse_Expire
}

func (this *FileResponse) GetErrorCode() int32 {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

func init() {
}
