// Code generated by protoc-gen-go.
// source: DailyLifeNotification.proto
// DO NOT EDIT!

package DLNotif

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ItemParam struct {
	ItemId           *int64 `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ItemParam) Reset()         { *this = ItemParam{} }
func (this *ItemParam) String() string { return proto.CompactTextString(this) }
func (*ItemParam) ProtoMessage()       {}

func (this *ItemParam) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

type CommentParam struct {
	ItemId           *int64 `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	CommentId        *int64 `protobuf:"varint,2,opt,name=comment_id" json:"comment_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *CommentParam) Reset()         { *this = CommentParam{} }
func (this *CommentParam) String() string { return proto.CompactTextString(this) }
func (*CommentParam) ProtoMessage()       {}

func (this *CommentParam) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *CommentParam) GetCommentId() int64 {
	if this != nil && this.CommentId != nil {
		return *this.CommentId
	}
	return 0
}

func init() {
}
