// Code generated by protoc-gen-go.
// source: dailylife.proto
// DO NOT EDIT!

package DL

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ResultAck_RequestType int32

const (
	ResultAck_RecentPost     ResultAck_RequestType = 0
	ResultAck_DeletedItemIds ResultAck_RequestType = 1
)

var ResultAck_RequestType_name = map[int32]string{
	0: "RecentPost",
	1: "DeletedItemIds",
}
var ResultAck_RequestType_value = map[string]int32{
	"RecentPost":     0,
	"DeletedItemIds": 1,
}

func (x ResultAck_RequestType) Enum() *ResultAck_RequestType {
	p := new(ResultAck_RequestType)
	*p = x
	return p
}
func (x ResultAck_RequestType) String() string {
	return proto.EnumName(ResultAck_RequestType_name, int32(x))
}
func (x ResultAck_RequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ResultAck_RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResultAck_RequestType_value, data, "ResultAck_RequestType")
	if err != nil {
		return err
	}
	*x = ResultAck_RequestType(value)
	return nil
}

type DailyBasicInfo struct {
	Address          *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Timestamp        *int32  `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Option           *string `protobuf:"bytes,3,opt,name=option" json:"option,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DailyBasicInfo) Reset()         { *this = DailyBasicInfo{} }
func (this *DailyBasicInfo) String() string { return proto.CompactTextString(this) }
func (*DailyBasicInfo) ProtoMessage()       {}

func (this *DailyBasicInfo) GetAddress() string {
	if this != nil && this.Address != nil {
		return *this.Address
	}
	return ""
}

func (this *DailyBasicInfo) GetTimestamp() int32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *DailyBasicInfo) GetOption() string {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return ""
}

type PhotoInfo struct {
	Name             []byte  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Memo             *string `protobuf:"bytes,2,opt,name=memo" json:"memo,omitempty"`
	MetaTag          *string `protobuf:"bytes,3,opt,name=meta_tag" json:"meta_tag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *PhotoInfo) Reset()         { *this = PhotoInfo{} }
func (this *PhotoInfo) String() string { return proto.CompactTextString(this) }
func (*PhotoInfo) ProtoMessage()       {}

func (this *PhotoInfo) GetName() []byte {
	if this != nil {
		return this.Name
	}
	return nil
}

func (this *PhotoInfo) GetMemo() string {
	if this != nil && this.Memo != nil {
		return *this.Memo
	}
	return ""
}

func (this *PhotoInfo) GetMetaTag() string {
	if this != nil && this.MetaTag != nil {
		return *this.MetaTag
	}
	return ""
}

type DailyItem struct {
	ItemId           *int64          `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	BasicInfo        *DailyBasicInfo `protobuf:"bytes,2,req,name=basic_info" json:"basic_info,omitempty"`
	PhotoInfo        []*PhotoInfo    `protobuf:"bytes,3,rep,name=photo_info" json:"photo_info,omitempty"`
	Memo             *string         `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	ShareMode        *int32          `protobuf:"varint,5,opt,name=share_mode" json:"share_mode,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *DailyItem) Reset()         { *this = DailyItem{} }
func (this *DailyItem) String() string { return proto.CompactTextString(this) }
func (*DailyItem) ProtoMessage()       {}

func (this *DailyItem) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *DailyItem) GetBasicInfo() *DailyBasicInfo {
	if this != nil {
		return this.BasicInfo
	}
	return nil
}

func (this *DailyItem) GetMemo() string {
	if this != nil && this.Memo != nil {
		return *this.Memo
	}
	return ""
}

func (this *DailyItem) GetShareMode() int32 {
	if this != nil && this.ShareMode != nil {
		return *this.ShareMode
	}
	return 0
}

type UserDailyItem struct {
	UserId           *int32       `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	DailyItem        []*DailyItem `protobuf:"bytes,2,rep,name=daily_item" json:"daily_item,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *UserDailyItem) Reset()         { *this = UserDailyItem{} }
func (this *UserDailyItem) String() string { return proto.CompactTextString(this) }
func (*UserDailyItem) ProtoMessage()       {}

func (this *UserDailyItem) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type ItemCircles struct {
	ItemId           *int64  `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	CircleIds        []int32 `protobuf:"varint,2,rep,name=circle_ids" json:"circle_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ItemCircles) Reset()         { *this = ItemCircles{} }
func (this *ItemCircles) String() string { return proto.CompactTextString(this) }
func (*ItemCircles) ProtoMessage()       {}

func (this *ItemCircles) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

type CommentInfo struct {
	Action           *string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Content          []byte  `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Timestamp        *int32  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CommentInfo) Reset()         { *this = CommentInfo{} }
func (this *CommentInfo) String() string { return proto.CompactTextString(this) }
func (*CommentInfo) ProtoMessage()       {}

func (this *CommentInfo) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *CommentInfo) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *CommentInfo) GetTimestamp() int32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

type Cursor struct {
	SeqNo            *int32 `protobuf:"varint,1,opt,name=seq_no" json:"seq_no,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Cursor) Reset()         { *this = Cursor{} }
func (this *Cursor) String() string { return proto.CompactTextString(this) }
func (*Cursor) ProtoMessage()       {}

func (this *Cursor) GetSeqNo() int32 {
	if this != nil && this.SeqNo != nil {
		return *this.SeqNo
	}
	return 0
}

type Circle struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32  `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	UserIds          []int32 `protobuf:"varint,3,rep,name=user_ids" json:"user_ids,omitempty"`
	Version          *int32  `protobuf:"varint,4,req,name=version" json:"version,omitempty"`
	Owner            *int32  `protobuf:"varint,5,opt,name=owner" json:"owner,omitempty"`
	Description      *string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Circle) Reset()         { *this = Circle{} }
func (this *Circle) String() string { return proto.CompactTextString(this) }
func (*Circle) ProtoMessage()       {}

func (this *Circle) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Circle) GetId() int32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Circle) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *Circle) GetOwner() int32 {
	if this != nil && this.Owner != nil {
		return *this.Owner
	}
	return 0
}

func (this *Circle) GetDescription() string {
	if this != nil && this.Description != nil {
		return *this.Description
	}
	return ""
}

type RequestDailyItems struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ItemIds          []int64 `protobuf:"varint,2,rep,name=item_ids" json:"item_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestDailyItems) Reset()         { *this = RequestDailyItems{} }
func (this *RequestDailyItems) String() string { return proto.CompactTextString(this) }
func (*RequestDailyItems) ProtoMessage()       {}

func (this *RequestDailyItems) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestIDList struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	CursorInfo       *Cursor `protobuf:"bytes,2,opt,name=cursor_info" json:"cursor_info,omitempty"`
	ItemCount        *int32  `protobuf:"varint,3,opt,name=item_count" json:"item_count,omitempty"`
	MaxId            *int64  `protobuf:"varint,4,opt,name=max_id" json:"max_id,omitempty"`
	MinId            *int64  `protobuf:"varint,5,opt,name=min_id" json:"min_id,omitempty"`
	BuddyId          *int32  `protobuf:"varint,6,opt,name=buddy_id" json:"buddy_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestIDList) Reset()         { *this = RequestIDList{} }
func (this *RequestIDList) String() string { return proto.CompactTextString(this) }
func (*RequestIDList) ProtoMessage()       {}

func (this *RequestIDList) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *RequestIDList) GetCursorInfo() *Cursor {
	if this != nil {
		return this.CursorInfo
	}
	return nil
}

func (this *RequestIDList) GetItemCount() int32 {
	if this != nil && this.ItemCount != nil {
		return *this.ItemCount
	}
	return 0
}

func (this *RequestIDList) GetMaxId() int64 {
	if this != nil && this.MaxId != nil {
		return *this.MaxId
	}
	return 0
}

func (this *RequestIDList) GetMinId() int64 {
	if this != nil && this.MinId != nil {
		return *this.MinId
	}
	return 0
}

func (this *RequestIDList) GetBuddyId() int32 {
	if this != nil && this.BuddyId != nil {
		return *this.BuddyId
	}
	return 0
}

type ResultAck struct {
	RequestId        []byte                 `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Type             *ResultAck_RequestType `protobuf:"varint,2,opt,name=type,enum=DL.ResultAck_RequestType" json:"type,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (this *ResultAck) Reset()         { *this = ResultAck{} }
func (this *ResultAck) String() string { return proto.CompactTextString(this) }
func (*ResultAck) ProtoMessage()       {}

func (this *ResultAck) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *ResultAck) GetType() ResultAck_RequestType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

type PostDailyItem struct {
	Item             *DailyItem `protobuf:"bytes,1,req,name=item" json:"item,omitempty"`
	RequestId        []byte     `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	Buddies          []int32    `protobuf:"varint,3,rep,name=buddies" json:"buddies,omitempty"`
	NoNotification   *bool      `protobuf:"varint,4,opt,name=no_notification" json:"no_notification,omitempty"`
	CircleIds        []int32    `protobuf:"varint,6,rep,name=circle_ids" json:"circle_ids,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *PostDailyItem) Reset()         { *this = PostDailyItem{} }
func (this *PostDailyItem) String() string { return proto.CompactTextString(this) }
func (*PostDailyItem) ProtoMessage()       {}

func (this *PostDailyItem) GetItem() *DailyItem {
	if this != nil {
		return this.Item
	}
	return nil
}

func (this *PostDailyItem) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *PostDailyItem) GetNoNotification() bool {
	if this != nil && this.NoNotification != nil {
		return *this.NoNotification
	}
	return false
}

type DeleteDailyItem struct {
	ItemId           *int64 `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	RequestId        []byte `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *DeleteDailyItem) Reset()         { *this = DeleteDailyItem{} }
func (this *DeleteDailyItem) String() string { return proto.CompactTextString(this) }
func (*DeleteDailyItem) ProtoMessage()       {}

func (this *DeleteDailyItem) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *DeleteDailyItem) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type PostComment struct {
	ItemId           *int64       `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	Comment          *CommentInfo `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
	RequestId        []byte       `protobuf:"bytes,3,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *PostComment) Reset()         { *this = PostComment{} }
func (this *PostComment) String() string { return proto.CompactTextString(this) }
func (*PostComment) ProtoMessage()       {}

func (this *PostComment) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *PostComment) GetComment() *CommentInfo {
	if this != nil {
		return this.Comment
	}
	return nil
}

func (this *PostComment) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestCommentDetail struct {
	ItemId           *int64 `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	RequestId        []byte `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	Version          *int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestCommentDetail) Reset()         { *this = RequestCommentDetail{} }
func (this *RequestCommentDetail) String() string { return proto.CompactTextString(this) }
func (*RequestCommentDetail) ProtoMessage()       {}

func (this *RequestCommentDetail) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *RequestCommentDetail) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *RequestCommentDetail) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type CommentRequest struct {
	CommentId        *int64 `protobuf:"varint,1,req,name=comment_id" json:"comment_id,omitempty"`
	Version          *int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *CommentRequest) Reset()         { *this = CommentRequest{} }
func (this *CommentRequest) String() string { return proto.CompactTextString(this) }
func (*CommentRequest) ProtoMessage()       {}

func (this *CommentRequest) GetCommentId() int64 {
	if this != nil && this.CommentId != nil {
		return *this.CommentId
	}
	return 0
}

func (this *CommentRequest) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type RequestCommentContent struct {
	CommentRequests  []*CommentRequest `protobuf:"bytes,1,rep,name=comment_requests" json:"comment_requests,omitempty"`
	RequestId        []byte            `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *RequestCommentContent) Reset()         { *this = RequestCommentContent{} }
func (this *RequestCommentContent) String() string { return proto.CompactTextString(this) }
func (*RequestCommentContent) ProtoMessage()       {}

func (this *RequestCommentContent) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestRecentPosts struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestRecentPosts) Reset()         { *this = RequestRecentPosts{} }
func (this *RequestRecentPosts) String() string { return proto.CompactTextString(this) }
func (*RequestRecentPosts) ProtoMessage()       {}

func (this *RequestRecentPosts) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestRecentSummary struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestRecentSummary) Reset()         { *this = RequestRecentSummary{} }
func (this *RequestRecentSummary) String() string { return proto.CompactTextString(this) }
func (*RequestRecentSummary) ProtoMessage()       {}

func (this *RequestRecentSummary) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type AddCircle struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Circle           *Circle `protobuf:"bytes,2,req,name=circle" json:"circle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *AddCircle) Reset()         { *this = AddCircle{} }
func (this *AddCircle) String() string { return proto.CompactTextString(this) }
func (*AddCircle) ProtoMessage()       {}

func (this *AddCircle) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *AddCircle) GetCircle() *Circle {
	if this != nil {
		return this.Circle
	}
	return nil
}

type AddCircleMember struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	CircleId         *int32  `protobuf:"varint,2,req,name=circle_id" json:"circle_id,omitempty"`
	UserIds          []int32 `protobuf:"varint,3,rep,name=user_ids" json:"user_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *AddCircleMember) Reset()         { *this = AddCircleMember{} }
func (this *AddCircleMember) String() string { return proto.CompactTextString(this) }
func (*AddCircleMember) ProtoMessage()       {}

func (this *AddCircleMember) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *AddCircleMember) GetCircleId() int32 {
	if this != nil && this.CircleId != nil {
		return *this.CircleId
	}
	return 0
}

type RemoveCircleMember struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	CircleId         *int32  `protobuf:"varint,2,req,name=circle_id" json:"circle_id,omitempty"`
	UserIds          []int32 `protobuf:"varint,3,rep,name=user_ids" json:"user_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoveCircleMember) Reset()         { *this = RemoveCircleMember{} }
func (this *RemoveCircleMember) String() string { return proto.CompactTextString(this) }
func (*RemoveCircleMember) ProtoMessage()       {}

func (this *RemoveCircleMember) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *RemoveCircleMember) GetCircleId() int32 {
	if this != nil && this.CircleId != nil {
		return *this.CircleId
	}
	return 0
}

type RemoveCircle struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	CircleIds        []int32 `protobuf:"varint,2,rep,name=circle_ids" json:"circle_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoveCircle) Reset()         { *this = RemoveCircle{} }
func (this *RemoveCircle) String() string { return proto.CompactTextString(this) }
func (*RemoveCircle) ProtoMessage()       {}

func (this *RemoveCircle) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestCircles struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Version          *int32 `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestCircles) Reset()         { *this = RequestCircles{} }
func (this *RequestCircles) String() string { return proto.CompactTextString(this) }
func (*RequestCircles) ProtoMessage()       {}

func (this *RequestCircles) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *RequestCircles) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type RequestItemCircles struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ItemIds          []int64 `protobuf:"varint,2,rep,name=item_ids" json:"item_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestItemCircles) Reset()         { *this = RequestItemCircles{} }
func (this *RequestItemCircles) String() string { return proto.CompactTextString(this) }
func (*RequestItemCircles) ProtoMessage()       {}

func (this *RequestItemCircles) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RemoveBuddy struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	BuddyIds         []int32 `protobuf:"varint,2,rep,name=buddy_ids" json:"buddy_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoveBuddy) Reset()         { *this = RemoveBuddy{} }
func (this *RemoveBuddy) String() string { return proto.CompactTextString(this) }
func (*RemoveBuddy) ProtoMessage()       {}

func (this *RemoveBuddy) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type OperationState struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ErrorCode        *int32 `protobuf:"varint,2,opt,name=error_code" json:"error_code,omitempty"`
	ItemId           *int64 `protobuf:"varint,3,opt,name=item_id" json:"item_id,omitempty"`
	CommentId        *int64 `protobuf:"varint,4,opt,name=comment_id" json:"comment_id,omitempty"`
	Version          *int32 `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *OperationState) Reset()         { *this = OperationState{} }
func (this *OperationState) String() string { return proto.CompactTextString(this) }
func (*OperationState) ProtoMessage()       {}

func (this *OperationState) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *OperationState) GetErrorCode() int32 {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

func (this *OperationState) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *OperationState) GetCommentId() int64 {
	if this != nil && this.CommentId != nil {
		return *this.CommentId
	}
	return 0
}

func (this *OperationState) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type DailyItemsResponse struct {
	RequestId        []byte           `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Items            []*UserDailyItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (this *DailyItemsResponse) Reset()         { *this = DailyItemsResponse{} }
func (this *DailyItemsResponse) String() string { return proto.CompactTextString(this) }
func (*DailyItemsResponse) ProtoMessage()       {}

func (this *DailyItemsResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type ItemCirclesResponse struct {
	RequestId        []byte         `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ItemCircles      []*ItemCircles `protobuf:"bytes,2,rep,name=item_circles" json:"item_circles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (this *ItemCirclesResponse) Reset()         { *this = ItemCirclesResponse{} }
func (this *ItemCirclesResponse) String() string { return proto.CompactTextString(this) }
func (*ItemCirclesResponse) ProtoMessage()       {}

func (this *ItemCirclesResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type IDListResponse struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Ids              []int64 `protobuf:"varint,2,rep,name=ids" json:"ids,omitempty"`
	CursorInfo       *Cursor `protobuf:"bytes,3,opt,name=cursor_info" json:"cursor_info,omitempty"`
	ItemCount        *int32  `protobuf:"varint,4,opt,name=item_count" json:"item_count,omitempty"`
	MaxId            *int64  `protobuf:"varint,5,opt,name=max_id" json:"max_id,omitempty"`
	MinId            *int64  `protobuf:"varint,6,opt,name=min_id" json:"min_id,omitempty"`
	BuddyId          *int32  `protobuf:"varint,7,opt,name=buddy_id" json:"buddy_id,omitempty"`
	DeletedIds       []int64 `protobuf:"varint,8,rep,name=deleted_ids" json:"deleted_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *IDListResponse) Reset()         { *this = IDListResponse{} }
func (this *IDListResponse) String() string { return proto.CompactTextString(this) }
func (*IDListResponse) ProtoMessage()       {}

func (this *IDListResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *IDListResponse) GetCursorInfo() *Cursor {
	if this != nil {
		return this.CursorInfo
	}
	return nil
}

func (this *IDListResponse) GetItemCount() int32 {
	if this != nil && this.ItemCount != nil {
		return *this.ItemCount
	}
	return 0
}

func (this *IDListResponse) GetMaxId() int64 {
	if this != nil && this.MaxId != nil {
		return *this.MaxId
	}
	return 0
}

func (this *IDListResponse) GetMinId() int64 {
	if this != nil && this.MinId != nil {
		return *this.MinId
	}
	return 0
}

func (this *IDListResponse) GetBuddyId() int32 {
	if this != nil && this.BuddyId != nil {
		return *this.BuddyId
	}
	return 0
}

type UserCommentInfo struct {
	UserId           *int32       `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Comment          *CommentInfo `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
	CommentId        *int64       `protobuf:"varint,3,opt,name=comment_id" json:"comment_id,omitempty"`
	Version          *int32       `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	ItemId           *int64       `protobuf:"varint,5,opt,name=item_id" json:"item_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *UserCommentInfo) Reset()         { *this = UserCommentInfo{} }
func (this *UserCommentInfo) String() string { return proto.CompactTextString(this) }
func (*UserCommentInfo) ProtoMessage()       {}

func (this *UserCommentInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *UserCommentInfo) GetComment() *CommentInfo {
	if this != nil {
		return this.Comment
	}
	return nil
}

func (this *UserCommentInfo) GetCommentId() int64 {
	if this != nil && this.CommentId != nil {
		return *this.CommentId
	}
	return 0
}

func (this *UserCommentInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *UserCommentInfo) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

type CommentDetailResponse struct {
	ItemId           *int64             `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	Comments         []*UserCommentInfo `protobuf:"bytes,2,rep,name=comments" json:"comments,omitempty"`
	Version          *int32             `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *CommentDetailResponse) Reset()         { *this = CommentDetailResponse{} }
func (this *CommentDetailResponse) String() string { return proto.CompactTextString(this) }
func (*CommentDetailResponse) ProtoMessage()       {}

func (this *CommentDetailResponse) GetItemId() int64 {
	if this != nil && this.ItemId != nil {
		return *this.ItemId
	}
	return 0
}

func (this *CommentDetailResponse) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type CommentContentResponse struct {
	RequestId        []byte             `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Comments         []*UserCommentInfo `protobuf:"bytes,2,rep,name=comments" json:"comments,omitempty"`
	TotalCount       *int32             `protobuf:"varint,3,opt,name=total_count" json:"total_count,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *CommentContentResponse) Reset()         { *this = CommentContentResponse{} }
func (this *CommentContentResponse) String() string { return proto.CompactTextString(this) }
func (*CommentContentResponse) ProtoMessage()       {}

func (this *CommentContentResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *CommentContentResponse) GetTotalCount() int32 {
	if this != nil && this.TotalCount != nil {
		return *this.TotalCount
	}
	return 0
}

type RecentPostsResponse struct {
	RequestId        []byte  `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ItemIds          []int64 `protobuf:"varint,2,rep,name=item_ids" json:"item_ids,omitempty"`
	CommentIds       []int64 `protobuf:"varint,3,rep,name=comment_ids" json:"comment_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RecentPostsResponse) Reset()         { *this = RecentPostsResponse{} }
func (this *RecentPostsResponse) String() string { return proto.CompactTextString(this) }
func (*RecentPostsResponse) ProtoMessage()       {}

func (this *RecentPostsResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RecentSummaryResponse struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ItemCount        *int32 `protobuf:"varint,2,req,name=item_count" json:"item_count,omitempty"`
	CommentCount     *int32 `protobuf:"varint,3,req,name=comment_count" json:"comment_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RecentSummaryResponse) Reset()         { *this = RecentSummaryResponse{} }
func (this *RecentSummaryResponse) String() string { return proto.CompactTextString(this) }
func (*RecentSummaryResponse) ProtoMessage()       {}

func (this *RecentSummaryResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *RecentSummaryResponse) GetItemCount() int32 {
	if this != nil && this.ItemCount != nil {
		return *this.ItemCount
	}
	return 0
}

func (this *RecentSummaryResponse) GetCommentCount() int32 {
	if this != nil && this.CommentCount != nil {
		return *this.CommentCount
	}
	return 0
}

type CirclesResponse struct {
	RequestId        []byte    `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Circles          []*Circle `protobuf:"bytes,2,rep,name=circles" json:"circles,omitempty"`
	Version          *int32    `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *CirclesResponse) Reset()         { *this = CirclesResponse{} }
func (this *CirclesResponse) String() string { return proto.CompactTextString(this) }
func (*CirclesResponse) ProtoMessage()       {}

func (this *CirclesResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *CirclesResponse) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func init() {
	proto.RegisterEnum("DL.ResultAck_RequestType", ResultAck_RequestType_name, ResultAck_RequestType_value)
}
