// Code generated by protoc-gen-go.
// source: S2CBuddyProtocol.proto
// DO NOT EDIT!

package Auth_Buddy_S2C

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import Auth_Buddy_Common "CommonBuddyProtocol.pb"
import P_Common "CommonProtocol.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type EditCategoryError_EditCategoryErrorType int32

const (
	EditCategoryError_MAX_NUM_CATEGORY_REACHED EditCategoryError_EditCategoryErrorType = 1
)

var EditCategoryError_EditCategoryErrorType_name = map[int32]string{
	1: "MAX_NUM_CATEGORY_REACHED",
}
var EditCategoryError_EditCategoryErrorType_value = map[string]int32{
	"MAX_NUM_CATEGORY_REACHED": 1,
}

func (x EditCategoryError_EditCategoryErrorType) Enum() *EditCategoryError_EditCategoryErrorType {
	p := new(EditCategoryError_EditCategoryErrorType)
	*p = x
	return p
}
func (x EditCategoryError_EditCategoryErrorType) String() string {
	return proto.EnumName(EditCategoryError_EditCategoryErrorType_name, int32(x))
}
func (x EditCategoryError_EditCategoryErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *EditCategoryError_EditCategoryErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EditCategoryError_EditCategoryErrorType_value, data, "EditCategoryError_EditCategoryErrorType")
	if err != nil {
		return err
	}
	*x = EditCategoryError_EditCategoryErrorType(value)
	return nil
}

type DeleteCategoryError_DeleteCategoryErrorType int32

const (
	DeleteCategoryError_CANNOT_DELETE_SYSTEM_CATEGORY DeleteCategoryError_DeleteCategoryErrorType = 1
	DeleteCategoryError_CATEGORY_DOES_NOT_EXIST       DeleteCategoryError_DeleteCategoryErrorType = 2
)

var DeleteCategoryError_DeleteCategoryErrorType_name = map[int32]string{
	1: "CANNOT_DELETE_SYSTEM_CATEGORY",
	2: "CATEGORY_DOES_NOT_EXIST",
}
var DeleteCategoryError_DeleteCategoryErrorType_value = map[string]int32{
	"CANNOT_DELETE_SYSTEM_CATEGORY": 1,
	"CATEGORY_DOES_NOT_EXIST":       2,
}

func (x DeleteCategoryError_DeleteCategoryErrorType) Enum() *DeleteCategoryError_DeleteCategoryErrorType {
	p := new(DeleteCategoryError_DeleteCategoryErrorType)
	*p = x
	return p
}
func (x DeleteCategoryError_DeleteCategoryErrorType) String() string {
	return proto.EnumName(DeleteCategoryError_DeleteCategoryErrorType_name, int32(x))
}
func (x DeleteCategoryError_DeleteCategoryErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DeleteCategoryError_DeleteCategoryErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeleteCategoryError_DeleteCategoryErrorType_value, data, "DeleteCategoryError_DeleteCategoryErrorType")
	if err != nil {
		return err
	}
	*x = DeleteCategoryError_DeleteCategoryErrorType(value)
	return nil
}

type RequestAddBuddyError_RequestAddBuddyErrorType int32

const (
	RequestAddBuddyError_MAX_NUM_BUDDIES_REACHED RequestAddBuddyError_RequestAddBuddyErrorType = 1
)

var RequestAddBuddyError_RequestAddBuddyErrorType_name = map[int32]string{
	1: "MAX_NUM_BUDDIES_REACHED",
}
var RequestAddBuddyError_RequestAddBuddyErrorType_value = map[string]int32{
	"MAX_NUM_BUDDIES_REACHED": 1,
}

func (x RequestAddBuddyError_RequestAddBuddyErrorType) Enum() *RequestAddBuddyError_RequestAddBuddyErrorType {
	p := new(RequestAddBuddyError_RequestAddBuddyErrorType)
	*p = x
	return p
}
func (x RequestAddBuddyError_RequestAddBuddyErrorType) String() string {
	return proto.EnumName(RequestAddBuddyError_RequestAddBuddyErrorType_name, int32(x))
}
func (x RequestAddBuddyError_RequestAddBuddyErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RequestAddBuddyError_RequestAddBuddyErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestAddBuddyError_RequestAddBuddyErrorType_value, data, "RequestAddBuddyError_RequestAddBuddyErrorType")
	if err != nil {
		return err
	}
	*x = RequestAddBuddyError_RequestAddBuddyErrorType(value)
	return nil
}

type DeleteBuddyError_DeleteBuddyErrorType int32

const (
	DeleteBuddyError_NOT_EXISTS DeleteBuddyError_DeleteBuddyErrorType = 1
)

var DeleteBuddyError_DeleteBuddyErrorType_name = map[int32]string{
	1: "NOT_EXISTS",
}
var DeleteBuddyError_DeleteBuddyErrorType_value = map[string]int32{
	"NOT_EXISTS": 1,
}

func (x DeleteBuddyError_DeleteBuddyErrorType) Enum() *DeleteBuddyError_DeleteBuddyErrorType {
	p := new(DeleteBuddyError_DeleteBuddyErrorType)
	*p = x
	return p
}
func (x DeleteBuddyError_DeleteBuddyErrorType) String() string {
	return proto.EnumName(DeleteBuddyError_DeleteBuddyErrorType_name, int32(x))
}
func (x DeleteBuddyError_DeleteBuddyErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DeleteBuddyError_DeleteBuddyErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeleteBuddyError_DeleteBuddyErrorType_value, data, "DeleteBuddyError_DeleteBuddyErrorType")
	if err != nil {
		return err
	}
	*x = DeleteBuddyError_DeleteBuddyErrorType(value)
	return nil
}

type RequestUserInfoError_RequestUserInfoErrorType int32

const (
	RequestUserInfoError_NOT_EXISTS RequestUserInfoError_RequestUserInfoErrorType = 1
)

var RequestUserInfoError_RequestUserInfoErrorType_name = map[int32]string{
	1: "NOT_EXISTS",
}
var RequestUserInfoError_RequestUserInfoErrorType_value = map[string]int32{
	"NOT_EXISTS": 1,
}

func (x RequestUserInfoError_RequestUserInfoErrorType) Enum() *RequestUserInfoError_RequestUserInfoErrorType {
	p := new(RequestUserInfoError_RequestUserInfoErrorType)
	*p = x
	return p
}
func (x RequestUserInfoError_RequestUserInfoErrorType) String() string {
	return proto.EnumName(RequestUserInfoError_RequestUserInfoErrorType_name, int32(x))
}
func (x RequestUserInfoError_RequestUserInfoErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RequestUserInfoError_RequestUserInfoErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestUserInfoError_RequestUserInfoErrorType_value, data, "RequestUserInfoError_RequestUserInfoErrorType")
	if err != nil {
		return err
	}
	*x = RequestUserInfoError_RequestUserInfoErrorType(value)
	return nil
}

type CategoryItem struct {
	CateId           *int32  `protobuf:"varint,1,req" json:"CateId,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CategoryItem) Reset()         { *this = CategoryItem{} }
func (this *CategoryItem) String() string { return proto.CompactTextString(this) }
func (*CategoryItem) ProtoMessage()       {}

func (this *CategoryItem) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

func (this *CategoryItem) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type CategoryList struct {
	Category         []*CategoryItem `protobuf:"bytes,1,rep" json:"Category,omitempty"`
	Version          *int32          `protobuf:"varint,2,req" json:"Version,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *CategoryList) Reset()         { *this = CategoryList{} }
func (this *CategoryList) String() string { return proto.CompactTextString(this) }
func (*CategoryList) ProtoMessage()       {}

func (this *CategoryList) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type EditCategoryError struct {
	Error            *EditCategoryError_EditCategoryErrorType `protobuf:"varint,1,req,enum=Auth.Buddy.S2C.EditCategoryError_EditCategoryErrorType" json:"Error,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (this *EditCategoryError) Reset()         { *this = EditCategoryError{} }
func (this *EditCategoryError) String() string { return proto.CompactTextString(this) }
func (*EditCategoryError) ProtoMessage()       {}

func (this *EditCategoryError) GetError() EditCategoryError_EditCategoryErrorType {
	if this != nil && this.Error != nil {
		return *this.Error
	}
	return 0
}

type EditCategoryResponse struct {
	Category         *CategoryItem `protobuf:"bytes,1,req" json:"Category,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *EditCategoryResponse) Reset()         { *this = EditCategoryResponse{} }
func (this *EditCategoryResponse) String() string { return proto.CompactTextString(this) }
func (*EditCategoryResponse) ProtoMessage()       {}

func (this *EditCategoryResponse) GetCategory() *CategoryItem {
	if this != nil {
		return this.Category
	}
	return nil
}

type DeleteCategoryError struct {
	Error            *DeleteCategoryError_DeleteCategoryErrorType `protobuf:"varint,1,req,enum=Auth.Buddy.S2C.DeleteCategoryError_DeleteCategoryErrorType" json:"Error,omitempty"`
	CateId           *int32                                       `protobuf:"varint,2,req" json:"CateId,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (this *DeleteCategoryError) Reset()         { *this = DeleteCategoryError{} }
func (this *DeleteCategoryError) String() string { return proto.CompactTextString(this) }
func (*DeleteCategoryError) ProtoMessage()       {}

func (this *DeleteCategoryError) GetError() DeleteCategoryError_DeleteCategoryErrorType {
	if this != nil && this.Error != nil {
		return *this.Error
	}
	return 0
}

func (this *DeleteCategoryError) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

type DeleteCategoryResponse struct {
	DeleteCategory   []int32 `protobuf:"varint,1,rep" json:"DeleteCategory,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DeleteCategoryResponse) Reset()         { *this = DeleteCategoryResponse{} }
func (this *DeleteCategoryResponse) String() string { return proto.CompactTextString(this) }
func (*DeleteCategoryResponse) ProtoMessage()       {}

type BuddyRelationInfo struct {
	CateId           *int32 `protobuf:"varint,1,req" json:"CateId,omitempty"`
	Relationship     *int32 `protobuf:"varint,2,req" json:"Relationship,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *BuddyRelationInfo) Reset()         { *this = BuddyRelationInfo{} }
func (this *BuddyRelationInfo) String() string { return proto.CompactTextString(this) }
func (*BuddyRelationInfo) ProtoMessage()       {}

func (this *BuddyRelationInfo) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

func (this *BuddyRelationInfo) GetRelationship() int32 {
	if this != nil && this.Relationship != nil {
		return *this.Relationship
	}
	return 0
}

type BuddySimpleInfoList struct {
	Buddies          []*BuddySimpleInfoList_BuddySimpleInfo `protobuf:"bytes,1,rep" json:"Buddies,omitempty"`
	RequestId        *int32                                 `protobuf:"varint,2,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (this *BuddySimpleInfoList) Reset()         { *this = BuddySimpleInfoList{} }
func (this *BuddySimpleInfoList) String() string { return proto.CompactTextString(this) }
func (*BuddySimpleInfoList) ProtoMessage()       {}

func (this *BuddySimpleInfoList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type BuddySimpleInfoList_BuddySimpleInfo struct {
	UserId           *int32             `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Info             *BuddyRelationInfo `protobuf:"bytes,2,req" json:"Info,omitempty"`
	Version          *int32             `protobuf:"varint,3,req" json:"Version,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *BuddySimpleInfoList_BuddySimpleInfo) Reset() {
	*this = BuddySimpleInfoList_BuddySimpleInfo{}
}
func (this *BuddySimpleInfoList_BuddySimpleInfo) String() string { return proto.CompactTextString(this) }
func (*BuddySimpleInfoList_BuddySimpleInfo) ProtoMessage()       {}

func (this *BuddySimpleInfoList_BuddySimpleInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *BuddySimpleInfoList_BuddySimpleInfo) GetInfo() *BuddyRelationInfo {
	if this != nil {
		return this.Info
	}
	return nil
}

func (this *BuddySimpleInfoList_BuddySimpleInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type UserInfo struct {
	Nickname         *string `protobuf:"bytes,1,req" json:"Nickname,omitempty"`
	Icon             *int64  `protobuf:"varint,2,req" json:"Icon,omitempty"`
	Exp              *int32  `protobuf:"varint,3,req" json:"Exp,omitempty"`
	Version          *int32  `protobuf:"varint,4,req" json:"Version,omitempty"`
	Gender           *int32  `protobuf:"varint,5,req" json:"Gender,omitempty"`
	Birthday         *int32  `protobuf:"varint,6,req" json:"Birthday,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *UserInfo) Reset()         { *this = UserInfo{} }
func (this *UserInfo) String() string { return proto.CompactTextString(this) }
func (*UserInfo) ProtoMessage()       {}

func (this *UserInfo) GetNickname() string {
	if this != nil && this.Nickname != nil {
		return *this.Nickname
	}
	return ""
}

func (this *UserInfo) GetIcon() int64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

func (this *UserInfo) GetExp() int32 {
	if this != nil && this.Exp != nil {
		return *this.Exp
	}
	return 0
}

func (this *UserInfo) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *UserInfo) GetGender() int32 {
	if this != nil && this.Gender != nil {
		return *this.Gender
	}
	return 0
}

func (this *UserInfo) GetBirthday() int32 {
	if this != nil && this.Birthday != nil {
		return *this.Birthday
	}
	return 0
}

type RequestAddBuddyError struct {
	UserId           *int32                `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Error            *RequestAddBuddyError `protobuf:"bytes,2,opt" json:"Error,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (this *RequestAddBuddyError) Reset()         { *this = RequestAddBuddyError{} }
func (this *RequestAddBuddyError) String() string { return proto.CompactTextString(this) }
func (*RequestAddBuddyError) ProtoMessage()       {}

func (this *RequestAddBuddyError) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RequestAddBuddyError) GetError() *RequestAddBuddyError {
	if this != nil {
		return this.Error
	}
	return nil
}

type RemoteAddBuddyResult struct {
	FromId           *int32 `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Action           *int32 `protobuf:"varint,2,opt" json:"Action,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RemoteAddBuddyResult) Reset()         { *this = RemoteAddBuddyResult{} }
func (this *RemoteAddBuddyResult) String() string { return proto.CompactTextString(this) }
func (*RemoteAddBuddyResult) ProtoMessage()       {}

func (this *RemoteAddBuddyResult) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteAddBuddyResult) GetAction() int32 {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return 0
}

type RemoteRequestAddBuddy struct {
	FromId           *int32  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Message          *string `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteRequestAddBuddy) Reset()         { *this = RemoteRequestAddBuddy{} }
func (this *RemoteRequestAddBuddy) String() string { return proto.CompactTextString(this) }
func (*RemoteRequestAddBuddy) ProtoMessage()       {}

func (this *RemoteRequestAddBuddy) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteRequestAddBuddy) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type BuddyDeleted struct {
	UserId           []int32 `protobuf:"varint,1,rep" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BuddyDeleted) Reset()         { *this = BuddyDeleted{} }
func (this *BuddyDeleted) String() string { return proto.CompactTextString(this) }
func (*BuddyDeleted) ProtoMessage()       {}

type DeleteBuddyError struct {
	UserId           *int32                                 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Error            *DeleteBuddyError_DeleteBuddyErrorType `protobuf:"varint,2,opt,enum=Auth.Buddy.S2C.DeleteBuddyError_DeleteBuddyErrorType" json:"Error,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (this *DeleteBuddyError) Reset()         { *this = DeleteBuddyError{} }
func (this *DeleteBuddyError) String() string { return proto.CompactTextString(this) }
func (*DeleteBuddyError) ProtoMessage()       {}

func (this *DeleteBuddyError) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *DeleteBuddyError) GetError() DeleteBuddyError_DeleteBuddyErrorType {
	if this != nil && this.Error != nil {
		return *this.Error
	}
	return 0
}

type ChangeBuddyCategoryResult struct {
	CateId           *int32  `protobuf:"varint,1,req" json:"CateId,omitempty"`
	BuddyId          []int32 `protobuf:"varint,2,rep" json:"BuddyId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeBuddyCategoryResult) Reset()         { *this = ChangeBuddyCategoryResult{} }
func (this *ChangeBuddyCategoryResult) String() string { return proto.CompactTextString(this) }
func (*ChangeBuddyCategoryResult) ProtoMessage()       {}

func (this *ChangeBuddyCategoryResult) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

type UserStatusInfo struct {
	Status           *Auth_Buddy_Common.UserOnlineStatus `protobuf:"varint,1,req,enum=Auth.Buddy.Common.UserOnlineStatus" json:"Status,omitempty"`
	MobileStatus     *int32                              `protobuf:"varint,3,opt" json:"MobileStatus,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (this *UserStatusInfo) Reset()         { *this = UserStatusInfo{} }
func (this *UserStatusInfo) String() string { return proto.CompactTextString(this) }
func (*UserStatusInfo) ProtoMessage()       {}

func (this *UserStatusInfo) GetStatus() Auth_Buddy_Common.UserOnlineStatus {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

func (this *UserStatusInfo) GetMobileStatus() int32 {
	if this != nil && this.MobileStatus != nil {
		return *this.MobileStatus
	}
	return 0
}

type BuddyInfo struct {
	UserId           *int32             `protobuf:"varint,1,req" json:"UserId,omitempty"`
	UserInfo         *UserInfo          `protobuf:"bytes,3,opt" json:"UserInfo,omitempty"`
	StatusInfo       *UserStatusInfo    `protobuf:"bytes,4,opt" json:"StatusInfo,omitempty"`
	RelationInfo     *BuddyRelationInfo `protobuf:"bytes,5,opt" json:"RelationInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *BuddyInfo) Reset()         { *this = BuddyInfo{} }
func (this *BuddyInfo) String() string { return proto.CompactTextString(this) }
func (*BuddyInfo) ProtoMessage()       {}

func (this *BuddyInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *BuddyInfo) GetUserInfo() *UserInfo {
	if this != nil {
		return this.UserInfo
	}
	return nil
}

func (this *BuddyInfo) GetStatusInfo() *UserStatusInfo {
	if this != nil {
		return this.StatusInfo
	}
	return nil
}

func (this *BuddyInfo) GetRelationInfo() *BuddyRelationInfo {
	if this != nil {
		return this.RelationInfo
	}
	return nil
}

type BuddyInfoList struct {
	Buddies          []*BuddyInfo `protobuf:"bytes,1,rep" json:"Buddies,omitempty"`
	RequestId        *int32       `protobuf:"varint,2,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *BuddyInfoList) Reset()         { *this = BuddyInfoList{} }
func (this *BuddyInfoList) String() string { return proto.CompactTextString(this) }
func (*BuddyInfoList) ProtoMessage()       {}

func (this *BuddyInfoList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type UserSignatureInfo struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Signature        []byte `protobuf:"bytes,2,opt" json:"Signature,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *UserSignatureInfo) Reset()         { *this = UserSignatureInfo{} }
func (this *UserSignatureInfo) String() string { return proto.CompactTextString(this) }
func (*UserSignatureInfo) ProtoMessage()       {}

func (this *UserSignatureInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *UserSignatureInfo) GetSignature() []byte {
	if this != nil {
		return this.Signature
	}
	return nil
}

type UserSignatureList struct {
	Sign             []*UserSignatureInfo `protobuf:"bytes,1,rep" json:"Sign,omitempty"`
	Version          *int32               `protobuf:"varint,2,opt" json:"Version,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *UserSignatureList) Reset()         { *this = UserSignatureList{} }
func (this *UserSignatureList) String() string { return proto.CompactTextString(this) }
func (*UserSignatureList) ProtoMessage()       {}

func (this *UserSignatureList) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type BuddyOnline struct {
	UserId           *int32          `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Status           *UserStatusInfo `protobuf:"bytes,2,req" json:"Status,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *BuddyOnline) Reset()         { *this = BuddyOnline{} }
func (this *BuddyOnline) String() string { return proto.CompactTextString(this) }
func (*BuddyOnline) ProtoMessage()       {}

func (this *BuddyOnline) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *BuddyOnline) GetStatus() *UserStatusInfo {
	if this != nil {
		return this.Status
	}
	return nil
}

type BuddyOnlineList struct {
	Buddies          []*BuddyOnline `protobuf:"bytes,1,rep" json:"Buddies,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (this *BuddyOnlineList) Reset()         { *this = BuddyOnlineList{} }
func (this *BuddyOnlineList) String() string { return proto.CompactTextString(this) }
func (*BuddyOnlineList) ProtoMessage()       {}

type MyInfoChanged struct {
	UserId           *int32                `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Info             *MyInfoChanged_MyInfo `protobuf:"bytes,2,req" json:"Info,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (this *MyInfoChanged) Reset()         { *this = MyInfoChanged{} }
func (this *MyInfoChanged) String() string { return proto.CompactTextString(this) }
func (*MyInfoChanged) ProtoMessage()       {}

func (this *MyInfoChanged) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *MyInfoChanged) GetInfo() *MyInfoChanged_MyInfo {
	if this != nil {
		return this.Info
	}
	return nil
}

type MyInfoChanged_MyInfo struct {
	UserInfo         *UserInfo       `protobuf:"bytes,1,opt" json:"UserInfo,omitempty"`
	StatusInfo       *UserStatusInfo `protobuf:"bytes,2,opt" json:"StatusInfo,omitempty"`
	Signature        []byte          `protobuf:"bytes,3,opt" json:"Signature,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *MyInfoChanged_MyInfo) Reset()         { *this = MyInfoChanged_MyInfo{} }
func (this *MyInfoChanged_MyInfo) String() string { return proto.CompactTextString(this) }
func (*MyInfoChanged_MyInfo) ProtoMessage()       {}

func (this *MyInfoChanged_MyInfo) GetUserInfo() *UserInfo {
	if this != nil {
		return this.UserInfo
	}
	return nil
}

func (this *MyInfoChanged_MyInfo) GetStatusInfo() *UserStatusInfo {
	if this != nil {
		return this.StatusInfo
	}
	return nil
}

func (this *MyInfoChanged_MyInfo) GetSignature() []byte {
	if this != nil {
		return this.Signature
	}
	return nil
}

type ChatInfo struct {
	FromId           *int32                  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Message          []byte                  `protobuf:"bytes,2,req" json:"Message,omitempty"`
	Font             *P_Common.FontStyleInfo `protobuf:"bytes,3,opt" json:"Font,omitempty"`
	Timestamp        *int32                  `protobuf:"varint,4,opt" json:"Timestamp,omitempty"`
	RemoteMsgId      *int32                  `protobuf:"varint,5,opt" json:"RemoteMsgId,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (this *ChatInfo) Reset()         { *this = ChatInfo{} }
func (this *ChatInfo) String() string { return proto.CompactTextString(this) }
func (*ChatInfo) ProtoMessage()       {}

func (this *ChatInfo) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *ChatInfo) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *ChatInfo) GetFont() *P_Common.FontStyleInfo {
	if this != nil {
		return this.Font
	}
	return nil
}

func (this *ChatInfo) GetTimestamp() int32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *ChatInfo) GetRemoteMsgId() int32 {
	if this != nil && this.RemoteMsgId != nil {
		return *this.RemoteMsgId
	}
	return 0
}

type ChatAck struct {
	MsgId            *int32 `protobuf:"varint,1,req" json:"MsgId,omitempty"`
	Option           *int32 `protobuf:"varint,2,opt" json:"Option,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatAck) Reset()         { *this = ChatAck{} }
func (this *ChatAck) String() string { return proto.CompactTextString(this) }
func (*ChatAck) ProtoMessage()       {}

func (this *ChatAck) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *ChatAck) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

type RemoteChatAck struct {
	FromId           *int32 `protobuf:"varint,1,req" json:"FromId,omitempty"`
	MsgId            *int32 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RemoteChatAck) Reset()         { *this = RemoteChatAck{} }
func (this *RemoteChatAck) String() string { return proto.CompactTextString(this) }
func (*RemoteChatAck) ProtoMessage()       {}

func (this *RemoteChatAck) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteChatAck) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type ChatMediaInfo struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Message          []byte `protobuf:"bytes,3,req" json:"Message,omitempty"`
	Timestamp        *int32 `protobuf:"varint,4,opt" json:"Timestamp,omitempty"`
	RemoteMsgId      *int32 `protobuf:"varint,5,opt" json:"RemoteMsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatMediaInfo) Reset()         { *this = ChatMediaInfo{} }
func (this *ChatMediaInfo) String() string { return proto.CompactTextString(this) }
func (*ChatMediaInfo) ProtoMessage()       {}

func (this *ChatMediaInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatMediaInfo) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *ChatMediaInfo) GetTimestamp() int32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *ChatMediaInfo) GetRemoteMsgId() int32 {
	if this != nil && this.RemoteMsgId != nil {
		return *this.RemoteMsgId
	}
	return 0
}

type ChatMediaInfoAck struct {
	MsgId            *int32 `protobuf:"varint,1,req" json:"MsgId,omitempty"`
	Option           *int32 `protobuf:"varint,2,opt" json:"Option,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatMediaInfoAck) Reset()         { *this = ChatMediaInfoAck{} }
func (this *ChatMediaInfoAck) String() string { return proto.CompactTextString(this) }
func (*ChatMediaInfoAck) ProtoMessage()       {}

func (this *ChatMediaInfoAck) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *ChatMediaInfoAck) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

type ChatInfo2 struct {
	FromId           *int32  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	MetaTag          *string `protobuf:"bytes,2,opt" json:"MetaTag,omitempty"`
	Message          []byte  `protobuf:"bytes,3,req" json:"Message,omitempty"`
	Timestamp        *int32  `protobuf:"varint,4,opt" json:"Timestamp,omitempty"`
	MsgId            *int64  `protobuf:"varint,5,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChatInfo2) Reset()         { *this = ChatInfo2{} }
func (this *ChatInfo2) String() string { return proto.CompactTextString(this) }
func (*ChatInfo2) ProtoMessage()       {}

func (this *ChatInfo2) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *ChatInfo2) GetMetaTag() string {
	if this != nil && this.MetaTag != nil {
		return *this.MetaTag
	}
	return ""
}

func (this *ChatInfo2) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *ChatInfo2) GetTimestamp() int32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *ChatInfo2) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type Chat2Ack struct {
	MsgId            *int64 `protobuf:"varint,1,req" json:"MsgId,omitempty"`
	Option           *int32 `protobuf:"varint,2,opt" json:"Option,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Chat2Ack) Reset()         { *this = Chat2Ack{} }
func (this *Chat2Ack) String() string { return proto.CompactTextString(this) }
func (*Chat2Ack) ProtoMessage()       {}

func (this *Chat2Ack) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *Chat2Ack) GetOption() int32 {
	if this != nil && this.Option != nil {
		return *this.Option
	}
	return 0
}

type RemoteChat2Ack struct {
	FromId           *int32 `protobuf:"varint,1,req" json:"FromId,omitempty"`
	MsgId            *int64 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RemoteChat2Ack) Reset()         { *this = RemoteChat2Ack{} }
func (this *RemoteChat2Ack) String() string { return proto.CompactTextString(this) }
func (*RemoteChat2Ack) ProtoMessage()       {}

func (this *RemoteChat2Ack) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteChat2Ack) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type RequestUserInfoResult struct {
	UserId           *int32    `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Signature        []byte    `protobuf:"bytes,2,opt" json:"Signature,omitempty"`
	UserInfo         *UserInfo `protobuf:"bytes,3,opt" json:"UserInfo,omitempty"`
	RequestId        *int32    `protobuf:"varint,4,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *RequestUserInfoResult) Reset()         { *this = RequestUserInfoResult{} }
func (this *RequestUserInfoResult) String() string { return proto.CompactTextString(this) }
func (*RequestUserInfoResult) ProtoMessage()       {}

func (this *RequestUserInfoResult) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RequestUserInfoResult) GetSignature() []byte {
	if this != nil {
		return this.Signature
	}
	return nil
}

func (this *RequestUserInfoResult) GetUserInfo() *UserInfo {
	if this != nil {
		return this.UserInfo
	}
	return nil
}

func (this *RequestUserInfoResult) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type RequestUserInfoError struct {
	RequestId        *int32                                         `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	Error            *RequestUserInfoError_RequestUserInfoErrorType `protobuf:"varint,2,req,enum=Auth.Buddy.S2C.RequestUserInfoError_RequestUserInfoErrorType" json:"Error,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (this *RequestUserInfoError) Reset()         { *this = RequestUserInfoError{} }
func (this *RequestUserInfoError) String() string { return proto.CompactTextString(this) }
func (*RequestUserInfoError) ProtoMessage()       {}

func (this *RequestUserInfoError) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

func (this *RequestUserInfoError) GetError() RequestUserInfoError_RequestUserInfoErrorType {
	if this != nil && this.Error != nil {
		return *this.Error
	}
	return 0
}

type RemoteP2PRequest struct {
	FromId           *int32  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	Token            *string `protobuf:"bytes,4,opt" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteP2PRequest) Reset()         { *this = RemoteP2PRequest{} }
func (this *RemoteP2PRequest) String() string { return proto.CompactTextString(this) }
func (*RemoteP2PRequest) ProtoMessage()       {}

func (this *RemoteP2PRequest) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteP2PRequest) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *RemoteP2PRequest) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *RemoteP2PRequest) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type RemoteP2PResponse struct {
	FromId           *int32  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	Token            *string `protobuf:"bytes,4,opt" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteP2PResponse) Reset()         { *this = RemoteP2PResponse{} }
func (this *RemoteP2PResponse) String() string { return proto.CompactTextString(this) }
func (*RemoteP2PResponse) ProtoMessage()       {}

func (this *RemoteP2PResponse) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteP2PResponse) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *RemoteP2PResponse) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *RemoteP2PResponse) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type RemoteP2PResponseAck struct {
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	Token            *string `protobuf:"bytes,4,opt" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteP2PResponseAck) Reset()         { *this = RemoteP2PResponseAck{} }
func (this *RemoteP2PResponseAck) String() string { return proto.CompactTextString(this) }
func (*RemoteP2PResponseAck) ProtoMessage()       {}

func (this *RemoteP2PResponseAck) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *RemoteP2PResponseAck) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *RemoteP2PResponseAck) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type RemoteDoActionCode struct {
	FromId           *int32  `protobuf:"varint,1,req" json:"FromId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RemoteDoActionCode) Reset()         { *this = RemoteDoActionCode{} }
func (this *RemoteDoActionCode) String() string { return proto.CompactTextString(this) }
func (*RemoteDoActionCode) ProtoMessage()       {}

func (this *RemoteDoActionCode) GetFromId() int32 {
	if this != nil && this.FromId != nil {
		return *this.FromId
	}
	return 0
}

func (this *RemoteDoActionCode) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *RemoteDoActionCode) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type BuddyCurrChannelInfo struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	ChannelId        *int32  `protobuf:"varint,2,req" json:"ChannelId,omitempty"`
	SubChannelId     *int32  `protobuf:"varint,3,req" json:"SubChannelId,omitempty"`
	DisplayName      *string `protobuf:"bytes,4,opt" json:"DisplayName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BuddyCurrChannelInfo) Reset()         { *this = BuddyCurrChannelInfo{} }
func (this *BuddyCurrChannelInfo) String() string { return proto.CompactTextString(this) }
func (*BuddyCurrChannelInfo) ProtoMessage()       {}

func (this *BuddyCurrChannelInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *BuddyCurrChannelInfo) GetChannelId() int32 {
	if this != nil && this.ChannelId != nil {
		return *this.ChannelId
	}
	return 0
}

func (this *BuddyCurrChannelInfo) GetSubChannelId() int32 {
	if this != nil && this.SubChannelId != nil {
		return *this.SubChannelId
	}
	return 0
}

func (this *BuddyCurrChannelInfo) GetDisplayName() string {
	if this != nil && this.DisplayName != nil {
		return *this.DisplayName
	}
	return ""
}

type ChangeBuddyCurrChannel struct {
	Info             *BuddyCurrChannelInfo `protobuf:"bytes,1,req" json:"Info,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (this *ChangeBuddyCurrChannel) Reset()         { *this = ChangeBuddyCurrChannel{} }
func (this *ChangeBuddyCurrChannel) String() string { return proto.CompactTextString(this) }
func (*ChangeBuddyCurrChannel) ProtoMessage()       {}

func (this *ChangeBuddyCurrChannel) GetInfo() *BuddyCurrChannelInfo {
	if this != nil {
		return this.Info
	}
	return nil
}

type BuddyCurrChannelList struct {
	Buddies          []*BuddyCurrChannelInfo `protobuf:"bytes,1,rep" json:"Buddies,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (this *BuddyCurrChannelList) Reset()         { *this = BuddyCurrChannelList{} }
func (this *BuddyCurrChannelList) String() string { return proto.CompactTextString(this) }
func (*BuddyCurrChannelList) ProtoMessage()       {}

type ChangeMeMemDataResult struct {
	RequestId        []byte `protobuf:"bytes,1,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChangeMeMemDataResult) Reset()         { *this = ChangeMeMemDataResult{} }
func (this *ChangeMeMemDataResult) String() string { return proto.CompactTextString(this) }
func (*ChangeMeMemDataResult) ProtoMessage()       {}

func (this *ChangeMeMemDataResult) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type BuddyMemDataItem struct {
	Tag              *string `protobuf:"bytes,2,opt" json:"Tag,omitempty"`
	Content          []byte  `protobuf:"bytes,3,opt" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BuddyMemDataItem) Reset()         { *this = BuddyMemDataItem{} }
func (this *BuddyMemDataItem) String() string { return proto.CompactTextString(this) }
func (*BuddyMemDataItem) ProtoMessage()       {}

func (this *BuddyMemDataItem) GetTag() string {
	if this != nil && this.Tag != nil {
		return *this.Tag
	}
	return ""
}

func (this *BuddyMemDataItem) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

type BuddyMemDataInfo struct {
	UserId           *int32              `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Items            []*BuddyMemDataItem `protobuf:"bytes,2,rep" json:"Items,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (this *BuddyMemDataInfo) Reset()         { *this = BuddyMemDataInfo{} }
func (this *BuddyMemDataInfo) String() string { return proto.CompactTextString(this) }
func (*BuddyMemDataInfo) ProtoMessage()       {}

func (this *BuddyMemDataInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type RequestAllBuddyMemDataResult struct {
	Items            []*BuddyMemDataInfo `protobuf:"bytes,1,rep" json:"Items,omitempty"`
	Version          *int32              `protobuf:"varint,2,req" json:"Version,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (this *RequestAllBuddyMemDataResult) Reset()         { *this = RequestAllBuddyMemDataResult{} }
func (this *RequestAllBuddyMemDataResult) String() string { return proto.CompactTextString(this) }
func (*RequestAllBuddyMemDataResult) ProtoMessage()       {}

func (this *RequestAllBuddyMemDataResult) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type MobileUserLocationResponse struct {
	Action           *string                                              `protobuf:"bytes,1,req" json:"Action,omitempty"`
	User             []*MobileUserLocationResponse_MobileUserLocationInfo `protobuf:"bytes,2,rep" json:"User,omitempty"`
	RequestId        *string                                              `protobuf:"bytes,3,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte                                               `json:"-"`
}

func (this *MobileUserLocationResponse) Reset()         { *this = MobileUserLocationResponse{} }
func (this *MobileUserLocationResponse) String() string { return proto.CompactTextString(this) }
func (*MobileUserLocationResponse) ProtoMessage()       {}

func (this *MobileUserLocationResponse) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *MobileUserLocationResponse) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type MobileUserLocationResponse_MobileUserLocationInfo struct {
	UserId           *int32   `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Latitude         *float32 `protobuf:"fixed32,2,opt" json:"Latitude,omitempty"`
	Longitude        *float32 `protobuf:"fixed32,3,opt" json:"Longitude,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *MobileUserLocationResponse_MobileUserLocationInfo) Reset() {
	*this = MobileUserLocationResponse_MobileUserLocationInfo{}
}
func (this *MobileUserLocationResponse_MobileUserLocationInfo) String() string {
	return proto.CompactTextString(this)
}
func (*MobileUserLocationResponse_MobileUserLocationInfo) ProtoMessage() {}

func (this *MobileUserLocationResponse_MobileUserLocationInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *MobileUserLocationResponse_MobileUserLocationInfo) GetLatitude() float32 {
	if this != nil && this.Latitude != nil {
		return *this.Latitude
	}
	return 0
}

func (this *MobileUserLocationResponse_MobileUserLocationInfo) GetLongitude() float32 {
	if this != nil && this.Longitude != nil {
		return *this.Longitude
	}
	return 0
}

func init() {
	proto.RegisterEnum("Auth.Buddy.S2C.EditCategoryError_EditCategoryErrorType", EditCategoryError_EditCategoryErrorType_name, EditCategoryError_EditCategoryErrorType_value)
	proto.RegisterEnum("Auth.Buddy.S2C.DeleteCategoryError_DeleteCategoryErrorType", DeleteCategoryError_DeleteCategoryErrorType_name, DeleteCategoryError_DeleteCategoryErrorType_value)
	proto.RegisterEnum("Auth.Buddy.S2C.RequestAddBuddyError_RequestAddBuddyErrorType", RequestAddBuddyError_RequestAddBuddyErrorType_name, RequestAddBuddyError_RequestAddBuddyErrorType_value)
	proto.RegisterEnum("Auth.Buddy.S2C.DeleteBuddyError_DeleteBuddyErrorType", DeleteBuddyError_DeleteBuddyErrorType_name, DeleteBuddyError_DeleteBuddyErrorType_value)
	proto.RegisterEnum("Auth.Buddy.S2C.RequestUserInfoError_RequestUserInfoErrorType", RequestUserInfoError_RequestUserInfoErrorType_name, RequestUserInfoError_RequestUserInfoErrorType_value)
}
