// Code generated by protoc-gen-go.
// source: AuthS2CProtocol.proto
// DO NOT EDIT!

package Auth_S2C

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import TOKEN_S "garena.com/btalkTest/TOKEN_S"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ErrorInfo struct {
	Type             *int32  `protobuf:"varint,1,req" json:"Type,omitempty"`
	Reason           *string `protobuf:"bytes,2,opt" json:"Reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ErrorInfo) Reset()         { *this = ErrorInfo{} }
func (this *ErrorInfo) String() string { return proto.CompactTextString(this) }
func (*ErrorInfo) ProtoMessage()       {}

func (this *ErrorInfo) GetType() int32 {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *ErrorInfo) GetReason() string {
	if this != nil && this.Reason != nil {
		return *this.Reason
	}
	return ""
}

type CheckVersionErrorInfo struct {
	ErrorCode        *int32  `protobuf:"varint,1,req" json:"ErrorCode,omitempty"`
	ClientType       *int32  `protobuf:"varint,2,req" json:"ClientType,omitempty"`
	ClientVersion    *int32  `protobuf:"varint,3,req" json:"ClientVersion,omitempty"`
	Url              *string `protobuf:"bytes,4,opt" json:"Url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CheckVersionErrorInfo) Reset()         { *this = CheckVersionErrorInfo{} }
func (this *CheckVersionErrorInfo) String() string { return proto.CompactTextString(this) }
func (*CheckVersionErrorInfo) ProtoMessage()       {}

func (this *CheckVersionErrorInfo) GetErrorCode() int32 {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

func (this *CheckVersionErrorInfo) GetClientType() int32 {
	if this != nil && this.ClientType != nil {
		return *this.ClientType
	}
	return 0
}

func (this *CheckVersionErrorInfo) GetClientVersion() int32 {
	if this != nil && this.ClientVersion != nil {
		return *this.ClientVersion
	}
	return 0
}

func (this *CheckVersionErrorInfo) GetUrl() string {
	if this != nil && this.Url != nil {
		return *this.Url
	}
	return ""
}

type HelloInfoResult struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *HelloInfoResult) Reset()         { *this = HelloInfoResult{} }
func (this *HelloInfoResult) String() string { return proto.CompactTextString(this) }
func (*HelloInfoResult) ProtoMessage()       {}

func (this *HelloInfoResult) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type LoginUserInfo struct {
	MyInfo           *TOKEN_S.UserInfo            `protobuf:"bytes,1,req" json:"MyInfo,omitempty"`
	LastLogin        *LoginUserInfo_LastLoginInfo `protobuf:"bytes,2,opt" json:"LastLogin,omitempty"`
	ServerTime       *int32                       `protobuf:"varint,3,opt" json:"ServerTime,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (this *LoginUserInfo) Reset()         { *this = LoginUserInfo{} }
func (this *LoginUserInfo) String() string { return proto.CompactTextString(this) }
func (*LoginUserInfo) ProtoMessage()       {}

func (this *LoginUserInfo) GetMyInfo() *TOKEN_S.UserInfo {
	if this != nil {
		return this.MyInfo
	}
	return nil
}

func (this *LoginUserInfo) GetLastLogin() *LoginUserInfo_LastLoginInfo {
	if this != nil {
		return this.LastLogin
	}
	return nil
}

func (this *LoginUserInfo) GetServerTime() int32 {
	if this != nil && this.ServerTime != nil {
		return *this.ServerTime
	}
	return 0
}

type LoginUserInfo_LastLoginInfo struct {
	IP               *int32  `protobuf:"varint,1,opt" json:"IP,omitempty"`
	Time             *int32  `protobuf:"varint,2,opt" json:"Time,omitempty"`
	Country          *string `protobuf:"bytes,3,opt" json:"Country,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LoginUserInfo_LastLoginInfo) Reset()         { *this = LoginUserInfo_LastLoginInfo{} }
func (this *LoginUserInfo_LastLoginInfo) String() string { return proto.CompactTextString(this) }
func (*LoginUserInfo_LastLoginInfo) ProtoMessage()       {}

func (this *LoginUserInfo_LastLoginInfo) GetIP() int32 {
	if this != nil && this.IP != nil {
		return *this.IP
	}
	return 0
}

func (this *LoginUserInfo_LastLoginInfo) GetTime() int32 {
	if this != nil && this.Time != nil {
		return *this.Time
	}
	return 0
}

func (this *LoginUserInfo_LastLoginInfo) GetCountry() string {
	if this != nil && this.Country != nil {
		return *this.Country
	}
	return ""
}

type LoginTokenInfo struct {
	Token            *string `protobuf:"bytes,1,req" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LoginTokenInfo) Reset()         { *this = LoginTokenInfo{} }
func (this *LoginTokenInfo) String() string { return proto.CompactTextString(this) }
func (*LoginTokenInfo) ProtoMessage()       {}

func (this *LoginTokenInfo) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func init() {
}
