// Code generated by protoc-gen-go.
// source: AccountBind.proto
// DO NOT EDIT!

package AccountBinding

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BoundAccount struct {
	Provider         *string `protobuf:"bytes,1,req,name=provider" json:"provider,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt,name=parameter" json:"parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BoundAccount) Reset()         { *this = BoundAccount{} }
func (this *BoundAccount) String() string { return proto.CompactTextString(this) }
func (*BoundAccount) ProtoMessage()       {}

func (this *BoundAccount) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return ""
}

func (this *BoundAccount) GetAccount() string {
	if this != nil && this.Account != nil {
		return *this.Account
	}
	return ""
}

func (this *BoundAccount) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type Contact struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Contact) Reset()         { *this = Contact{} }
func (this *Contact) String() string { return proto.CompactTextString(this) }
func (*Contact) ProtoMessage()       {}

func (this *Contact) GetAccount() string {
	if this != nil && this.Account != nil {
		return *this.Account
	}
	return ""
}

func (this *Contact) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type Buddy struct {
	UserId           *int32  `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Account          *string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Provider         *string `protobuf:"bytes,4,opt,name=provider,def=mobile" json:"provider,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Buddy) Reset()         { *this = Buddy{} }
func (this *Buddy) String() string { return proto.CompactTextString(this) }
func (*Buddy) ProtoMessage()       {}

const Default_Buddy_Provider string = "mobile"

func (this *Buddy) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *Buddy) GetAccount() string {
	if this != nil && this.Account != nil {
		return *this.Account
	}
	return ""
}

func (this *Buddy) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Buddy) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return Default_Buddy_Provider
}

type BindRequest struct {
	Account          *BoundAccount `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	RequestId        []byte        `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *BindRequest) Reset()         { *this = BindRequest{} }
func (this *BindRequest) String() string { return proto.CompactTextString(this) }
func (*BindRequest) ProtoMessage()       {}

func (this *BindRequest) GetAccount() *BoundAccount {
	if this != nil {
		return this.Account
	}
	return nil
}

func (this *BindRequest) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type UnBindRequest struct {
	Account          *BoundAccount `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	RequestId        []byte        `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *UnBindRequest) Reset()         { *this = UnBindRequest{} }
func (this *UnBindRequest) String() string { return proto.CompactTextString(this) }
func (*UnBindRequest) ProtoMessage()       {}

func (this *UnBindRequest) GetAccount() *BoundAccount {
	if this != nil {
		return this.Account
	}
	return nil
}

func (this *UnBindRequest) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type ContactUpdateRequest struct {
	RequestId        []byte     `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	OldVersion       *int32     `protobuf:"varint,2,opt,name=old_version" json:"old_version,omitempty"`
	AddedContacts    []*Contact `protobuf:"bytes,3,rep,name=added_contacts" json:"added_contacts,omitempty"`
	RemovedContacts  []*Contact `protobuf:"bytes,4,rep,name=removed_contacts" json:"removed_contacts,omitempty"`
	Provider         *string    `protobuf:"bytes,5,req,name=provider,def=mobile" json:"provider,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *ContactUpdateRequest) Reset()         { *this = ContactUpdateRequest{} }
func (this *ContactUpdateRequest) String() string { return proto.CompactTextString(this) }
func (*ContactUpdateRequest) ProtoMessage()       {}

const Default_ContactUpdateRequest_Provider string = "mobile"

func (this *ContactUpdateRequest) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *ContactUpdateRequest) GetOldVersion() int32 {
	if this != nil && this.OldVersion != nil {
		return *this.OldVersion
	}
	return 0
}

func (this *ContactUpdateRequest) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return Default_ContactUpdateRequest_Provider
}

type RequestBoundAccounts struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBoundAccounts) Reset()         { *this = RequestBoundAccounts{} }
func (this *RequestBoundAccounts) String() string { return proto.CompactTextString(this) }
func (*RequestBoundAccounts) ProtoMessage()       {}

func (this *RequestBoundAccounts) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestContactList struct {
	Version          *int32  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Provider         *string `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestContactList) Reset()         { *this = RequestContactList{} }
func (this *RequestContactList) String() string { return proto.CompactTextString(this) }
func (*RequestContactList) ProtoMessage()       {}

func (this *RequestContactList) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *RequestContactList) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return ""
}

type BindResponse struct {
	RequestId        []byte        `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Account          *BoundAccount `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *BindResponse) Reset()         { *this = BindResponse{} }
func (this *BindResponse) String() string { return proto.CompactTextString(this) }
func (*BindResponse) ProtoMessage()       {}

func (this *BindResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *BindResponse) GetAccount() *BoundAccount {
	if this != nil {
		return this.Account
	}
	return nil
}

type UnBindResponse struct {
	RequestId        []byte `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *UnBindResponse) Reset()         { *this = UnBindResponse{} }
func (this *UnBindResponse) String() string { return proto.CompactTextString(this) }
func (*UnBindResponse) ProtoMessage()       {}

func (this *UnBindResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type ContactUpdateResponse struct {
	RequestId           []byte   `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Version             *int32   `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	AddedBuddies        []*Buddy `protobuf:"bytes,3,rep,name=added_buddies" json:"added_buddies,omitempty"`
	BuddyRequests       []*Buddy `protobuf:"bytes,4,rep,name=buddy_requests" json:"buddy_requests,omitempty"`
	BuddyRecommendation []*Buddy `protobuf:"bytes,5,rep,name=buddy_recommendation" json:"buddy_recommendation,omitempty"`
	ExistingBuddies     []*Buddy `protobuf:"bytes,6,rep,name=existing_buddies" json:"existing_buddies,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (this *ContactUpdateResponse) Reset()         { *this = ContactUpdateResponse{} }
func (this *ContactUpdateResponse) String() string { return proto.CompactTextString(this) }
func (*ContactUpdateResponse) ProtoMessage()       {}

func (this *ContactUpdateResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

func (this *ContactUpdateResponse) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type BoundedAccountsResponse struct {
	Accounts         []*BoundAccount `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	RequestId        []byte          `protobuf:"bytes,2,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *BoundedAccountsResponse) Reset()         { *this = BoundedAccountsResponse{} }
func (this *BoundedAccountsResponse) String() string { return proto.CompactTextString(this) }
func (*BoundedAccountsResponse) ProtoMessage()       {}

func (this *BoundedAccountsResponse) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type ContactListResponse struct {
	Version          *int32   `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Contacts         []*Buddy `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
	Provider         *string  `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ContactListResponse) Reset()         { *this = ContactListResponse{} }
func (this *ContactListResponse) String() string { return proto.CompactTextString(this) }
func (*ContactListResponse) ProtoMessage()       {}

func (this *ContactListResponse) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func (this *ContactListResponse) GetProvider() string {
	if this != nil && this.Provider != nil {
		return *this.Provider
	}
	return ""
}

func init() {
}
