// Code generated by protoc-gen-go.
// source: C2SBuddyProtocol.proto
// DO NOT EDIT!

package Auth_Buddy_C2S

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import Auth_Buddy_Common "CommonBuddyProtocol.pb"
import P_Common "CommonProtocol.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RequestCategoryList struct {
	RequestId        *int32 `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	Version          *int32 `protobuf:"varint,2,req" json:"Version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestCategoryList) Reset()         { *this = RequestCategoryList{} }
func (this *RequestCategoryList) String() string { return proto.CompactTextString(this) }
func (*RequestCategoryList) ProtoMessage()       {}

func (this *RequestCategoryList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

func (this *RequestCategoryList) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type EditCategory struct {
	CateId           *int32  `protobuf:"varint,1,opt" json:"CateId,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *EditCategory) Reset()         { *this = EditCategory{} }
func (this *EditCategory) String() string { return proto.CompactTextString(this) }
func (*EditCategory) ProtoMessage()       {}

func (this *EditCategory) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

func (this *EditCategory) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type DeleteCategory struct {
	CateId           *int32 `protobuf:"varint,1,req" json:"CateId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *DeleteCategory) Reset()         { *this = DeleteCategory{} }
func (this *DeleteCategory) String() string { return proto.CompactTextString(this) }
func (*DeleteCategory) ProtoMessage()       {}

func (this *DeleteCategory) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

type RequestBuddyOnlineList struct {
	RequestId        *int32 `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBuddyOnlineList) Reset()         { *this = RequestBuddyOnlineList{} }
func (this *RequestBuddyOnlineList) String() string { return proto.CompactTextString(this) }
func (*RequestBuddyOnlineList) ProtoMessage()       {}

func (this *RequestBuddyOnlineList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type RequestBuddySimpleInfoList struct {
	RequestId        *int32 `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBuddySimpleInfoList) Reset()         { *this = RequestBuddySimpleInfoList{} }
func (this *RequestBuddySimpleInfoList) String() string { return proto.CompactTextString(this) }
func (*RequestBuddySimpleInfoList) ProtoMessage()       {}

func (this *RequestBuddySimpleInfoList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type RequestAddBuddy struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Message          *string `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestAddBuddy) Reset()         { *this = RequestAddBuddy{} }
func (this *RequestAddBuddy) String() string { return proto.CompactTextString(this) }
func (*RequestAddBuddy) ProtoMessage()       {}

func (this *RequestAddBuddy) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RequestAddBuddy) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type AddBuddyResult struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Action           *int32 `protobuf:"varint,2,req" json:"Action,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *AddBuddyResult) Reset()         { *this = AddBuddyResult{} }
func (this *AddBuddyResult) String() string { return proto.CompactTextString(this) }
func (*AddBuddyResult) ProtoMessage()       {}

func (this *AddBuddyResult) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *AddBuddyResult) GetAction() int32 {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return 0
}

type DeleteBuddy struct {
	UserId           []int32 `protobuf:"varint,1,rep" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DeleteBuddy) Reset()         { *this = DeleteBuddy{} }
func (this *DeleteBuddy) String() string { return proto.CompactTextString(this) }
func (*DeleteBuddy) ProtoMessage()       {}

type RequestBuddyInfo struct {
	Requests         []*RequestBuddyInfo_Request `protobuf:"bytes,1,rep" json:"Requests,omitempty"`
	RequestId        *int32                      `protobuf:"varint,2,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (this *RequestBuddyInfo) Reset()         { *this = RequestBuddyInfo{} }
func (this *RequestBuddyInfo) String() string { return proto.CompactTextString(this) }
func (*RequestBuddyInfo) ProtoMessage()       {}

func (this *RequestBuddyInfo) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type RequestBuddyInfo_Request struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Type             *int32 `protobuf:"varint,2,req" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBuddyInfo_Request) Reset()         { *this = RequestBuddyInfo_Request{} }
func (this *RequestBuddyInfo_Request) String() string { return proto.CompactTextString(this) }
func (*RequestBuddyInfo_Request) ProtoMessage()       {}

func (this *RequestBuddyInfo_Request) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RequestBuddyInfo_Request) GetType() int32 {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

type RequestSignature struct {
	UserId           []int32 `protobuf:"varint,1,rep" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestSignature) Reset()         { *this = RequestSignature{} }
func (this *RequestSignature) String() string { return proto.CompactTextString(this) }
func (*RequestSignature) ProtoMessage()       {}

type RequestBuddySignature struct {
	Version          *int32 `protobuf:"varint,1,req" json:"Version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBuddySignature) Reset()         { *this = RequestBuddySignature{} }
func (this *RequestBuddySignature) String() string { return proto.CompactTextString(this) }
func (*RequestBuddySignature) ProtoMessage()       {}

func (this *RequestBuddySignature) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type ChangeUserInfo struct {
	NewSignature     *ChangeUserInfo_ChangeSignature    `protobuf:"bytes,1,opt" json:"NewSignature,omitempty"`
	NewStatus        *ChangeUserInfo_ChangeOnlineStatus `protobuf:"bytes,2,opt" json:"NewStatus,omitempty"`
	NewInfo          *ChangeUserInfo_ChangeInfo         `protobuf:"bytes,3,opt" json:"NewInfo,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (this *ChangeUserInfo) Reset()         { *this = ChangeUserInfo{} }
func (this *ChangeUserInfo) String() string { return proto.CompactTextString(this) }
func (*ChangeUserInfo) ProtoMessage()       {}

func (this *ChangeUserInfo) GetNewSignature() *ChangeUserInfo_ChangeSignature {
	if this != nil {
		return this.NewSignature
	}
	return nil
}

func (this *ChangeUserInfo) GetNewStatus() *ChangeUserInfo_ChangeOnlineStatus {
	if this != nil {
		return this.NewStatus
	}
	return nil
}

func (this *ChangeUserInfo) GetNewInfo() *ChangeUserInfo_ChangeInfo {
	if this != nil {
		return this.NewInfo
	}
	return nil
}

type ChangeUserInfo_ChangeSignature struct {
	Signature        []byte `protobuf:"bytes,1,opt" json:"Signature,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChangeUserInfo_ChangeSignature) Reset()         { *this = ChangeUserInfo_ChangeSignature{} }
func (this *ChangeUserInfo_ChangeSignature) String() string { return proto.CompactTextString(this) }
func (*ChangeUserInfo_ChangeSignature) ProtoMessage()       {}

func (this *ChangeUserInfo_ChangeSignature) GetSignature() []byte {
	if this != nil {
		return this.Signature
	}
	return nil
}

type ChangeUserInfo_ChangeOnlineStatus struct {
	Status           *Auth_Buddy_Common.UserOnlineStatus `protobuf:"varint,1,req,enum=Auth.Buddy.Common.UserOnlineStatus" json:"Status,omitempty"`
	Memo             *string                             `protobuf:"bytes,2,opt" json:"Memo,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (this *ChangeUserInfo_ChangeOnlineStatus) Reset()         { *this = ChangeUserInfo_ChangeOnlineStatus{} }
func (this *ChangeUserInfo_ChangeOnlineStatus) String() string { return proto.CompactTextString(this) }
func (*ChangeUserInfo_ChangeOnlineStatus) ProtoMessage()       {}

func (this *ChangeUserInfo_ChangeOnlineStatus) GetStatus() Auth_Buddy_Common.UserOnlineStatus {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

func (this *ChangeUserInfo_ChangeOnlineStatus) GetMemo() string {
	if this != nil && this.Memo != nil {
		return *this.Memo
	}
	return ""
}

type ChangeUserInfo_ChangeInfo struct {
	Nickname         *string `protobuf:"bytes,1,opt" json:"Nickname,omitempty"`
	Icon             *int64  `protobuf:"varint,2,opt" json:"Icon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeUserInfo_ChangeInfo) Reset()         { *this = ChangeUserInfo_ChangeInfo{} }
func (this *ChangeUserInfo_ChangeInfo) String() string { return proto.CompactTextString(this) }
func (*ChangeUserInfo_ChangeInfo) ProtoMessage()       {}

func (this *ChangeUserInfo_ChangeInfo) GetNickname() string {
	if this != nil && this.Nickname != nil {
		return *this.Nickname
	}
	return ""
}

func (this *ChangeUserInfo_ChangeInfo) GetIcon() int64 {
	if this != nil && this.Icon != nil {
		return *this.Icon
	}
	return 0
}

type ChatInfo struct {
	UserId           *int32                  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	MsgId            *int32                  `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	Message          []byte                  `protobuf:"bytes,3,req" json:"Message,omitempty"`
	Font             *P_Common.FontStyleInfo `protobuf:"bytes,4,opt" json:"Font,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (this *ChatInfo) Reset()         { *this = ChatInfo{} }
func (this *ChatInfo) String() string { return proto.CompactTextString(this) }
func (*ChatInfo) ProtoMessage()       {}

func (this *ChatInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatInfo) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *ChatInfo) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *ChatInfo) GetFont() *P_Common.FontStyleInfo {
	if this != nil {
		return this.Font
	}
	return nil
}

type ChatAckRemote struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	MsgId            *int32 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatAckRemote) Reset()         { *this = ChatAckRemote{} }
func (this *ChatAckRemote) String() string { return proto.CompactTextString(this) }
func (*ChatAckRemote) ProtoMessage()       {}

func (this *ChatAckRemote) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatAckRemote) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type ChatMediaInfo struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	MsgId            *int32 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	Message          []byte `protobuf:"bytes,3,req" json:"Message,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChatMediaInfo) Reset()         { *this = ChatMediaInfo{} }
func (this *ChatMediaInfo) String() string { return proto.CompactTextString(this) }
func (*ChatMediaInfo) ProtoMessage()       {}

func (this *ChatMediaInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatMediaInfo) GetMsgId() int32 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *ChatMediaInfo) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

type ChatInfo2 struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	MsgId            *int64  `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	MetaTag          *string `protobuf:"bytes,3,opt" json:"MetaTag,omitempty"`
	Message          []byte  `protobuf:"bytes,4,req" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChatInfo2) Reset()         { *this = ChatInfo2{} }
func (this *ChatInfo2) String() string { return proto.CompactTextString(this) }
func (*ChatInfo2) ProtoMessage()       {}

func (this *ChatInfo2) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *ChatInfo2) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

func (this *ChatInfo2) GetMetaTag() string {
	if this != nil && this.MetaTag != nil {
		return *this.MetaTag
	}
	return ""
}

func (this *ChatInfo2) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

type Chat2AckRemote struct {
	UserId           *int32 `protobuf:"varint,1,req" json:"UserId,omitempty"`
	MsgId            *int64 `protobuf:"varint,2,req" json:"MsgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Chat2AckRemote) Reset()         { *this = Chat2AckRemote{} }
func (this *Chat2AckRemote) String() string { return proto.CompactTextString(this) }
func (*Chat2AckRemote) ProtoMessage()       {}

func (this *Chat2AckRemote) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *Chat2AckRemote) GetMsgId() int64 {
	if this != nil && this.MsgId != nil {
		return *this.MsgId
	}
	return 0
}

type RequestUserInfo struct {
	Name             *string `protobuf:"bytes,1,opt" json:"Name,omitempty"`
	UserId           *int32  `protobuf:"varint,2,opt" json:"UserId,omitempty"`
	RequestId        *int32  `protobuf:"varint,3,opt" json:"RequestId,omitempty"`
	NoSignature      *bool   `protobuf:"varint,4,opt" json:"NoSignature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestUserInfo) Reset()         { *this = RequestUserInfo{} }
func (this *RequestUserInfo) String() string { return proto.CompactTextString(this) }
func (*RequestUserInfo) ProtoMessage()       {}

func (this *RequestUserInfo) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *RequestUserInfo) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *RequestUserInfo) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

func (this *RequestUserInfo) GetNoSignature() bool {
	if this != nil && this.NoSignature != nil {
		return *this.NoSignature
	}
	return false
}

type ChangeBuddyCategory struct {
	CateId           *int32  `protobuf:"varint,1,req" json:"CateId,omitempty"`
	BuddyId          []int32 `protobuf:"varint,2,rep" json:"BuddyId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeBuddyCategory) Reset()         { *this = ChangeBuddyCategory{} }
func (this *ChangeBuddyCategory) String() string { return proto.CompactTextString(this) }
func (*ChangeBuddyCategory) ProtoMessage()       {}

func (this *ChangeBuddyCategory) GetCateId() int32 {
	if this != nil && this.CateId != nil {
		return *this.CateId
	}
	return 0
}

type P2PRequest struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	Token            *string `protobuf:"bytes,4,opt" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *P2PRequest) Reset()         { *this = P2PRequest{} }
func (this *P2PRequest) String() string { return proto.CompactTextString(this) }
func (*P2PRequest) ProtoMessage()       {}

func (this *P2PRequest) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *P2PRequest) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *P2PRequest) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *P2PRequest) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

type P2PResponse struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	Token            *string `protobuf:"bytes,4,opt" json:"Token,omitempty"`
	NeedAck          *bool   `protobuf:"varint,5,opt" json:"NeedAck,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *P2PResponse) Reset()         { *this = P2PResponse{} }
func (this *P2PResponse) String() string { return proto.CompactTextString(this) }
func (*P2PResponse) ProtoMessage()       {}

func (this *P2PResponse) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *P2PResponse) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *P2PResponse) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

func (this *P2PResponse) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *P2PResponse) GetNeedAck() bool {
	if this != nil && this.NeedAck != nil {
		return *this.NeedAck
	}
	return false
}

type DoActionCode struct {
	UserId           *int32  `protobuf:"varint,1,req" json:"UserId,omitempty"`
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	Parameter        []byte  `protobuf:"bytes,3,opt" json:"Parameter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DoActionCode) Reset()         { *this = DoActionCode{} }
func (this *DoActionCode) String() string { return proto.CompactTextString(this) }
func (*DoActionCode) ProtoMessage()       {}

func (this *DoActionCode) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

func (this *DoActionCode) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *DoActionCode) GetParameter() []byte {
	if this != nil {
		return this.Parameter
	}
	return nil
}

type ChangeMeMemData struct {
	Tag              *string `protobuf:"bytes,1,req" json:"Tag,omitempty"`
	Content          []byte  `protobuf:"bytes,2,opt" json:"Content,omitempty"`
	RequestId        []byte  `protobuf:"bytes,3,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeMeMemData) Reset()         { *this = ChangeMeMemData{} }
func (this *ChangeMeMemData) String() string { return proto.CompactTextString(this) }
func (*ChangeMeMemData) ProtoMessage()       {}

func (this *ChangeMeMemData) GetTag() string {
	if this != nil && this.Tag != nil {
		return *this.Tag
	}
	return ""
}

func (this *ChangeMeMemData) GetContent() []byte {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *ChangeMeMemData) GetRequestId() []byte {
	if this != nil {
		return this.RequestId
	}
	return nil
}

type RequestAllBuddyMemData struct {
	Tag              *string `protobuf:"bytes,1,opt" json:"Tag,omitempty"`
	Version          *int32  `protobuf:"varint,2,opt" json:"Version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestAllBuddyMemData) Reset()         { *this = RequestAllBuddyMemData{} }
func (this *RequestAllBuddyMemData) String() string { return proto.CompactTextString(this) }
func (*RequestAllBuddyMemData) ProtoMessage()       {}

func (this *RequestAllBuddyMemData) GetTag() string {
	if this != nil && this.Tag != nil {
		return *this.Tag
	}
	return ""
}

func (this *RequestAllBuddyMemData) GetVersion() int32 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type RequestOneBuddyMemData struct {
	Tag              *string `protobuf:"bytes,1,opt" json:"Tag,omitempty"`
	UserId           *int32  `protobuf:"varint,2,req" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RequestOneBuddyMemData) Reset()         { *this = RequestOneBuddyMemData{} }
func (this *RequestOneBuddyMemData) String() string { return proto.CompactTextString(this) }
func (*RequestOneBuddyMemData) ProtoMessage()       {}

func (this *RequestOneBuddyMemData) GetTag() string {
	if this != nil && this.Tag != nil {
		return *this.Tag
	}
	return ""
}

func (this *RequestOneBuddyMemData) GetUserId() int32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type ChangeMyCurrChannel struct {
	ChannelId        *int32  `protobuf:"varint,1,req" json:"ChannelId,omitempty"`
	SubChannelId     *int32  `protobuf:"varint,2,req" json:"SubChannelId,omitempty"`
	DisplayName      *string `protobuf:"bytes,3,opt" json:"DisplayName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChangeMyCurrChannel) Reset()         { *this = ChangeMyCurrChannel{} }
func (this *ChangeMyCurrChannel) String() string { return proto.CompactTextString(this) }
func (*ChangeMyCurrChannel) ProtoMessage()       {}

func (this *ChangeMyCurrChannel) GetChannelId() int32 {
	if this != nil && this.ChannelId != nil {
		return *this.ChannelId
	}
	return 0
}

func (this *ChangeMyCurrChannel) GetSubChannelId() int32 {
	if this != nil && this.SubChannelId != nil {
		return *this.SubChannelId
	}
	return 0
}

func (this *ChangeMyCurrChannel) GetDisplayName() string {
	if this != nil && this.DisplayName != nil {
		return *this.DisplayName
	}
	return ""
}

type RequestBuddyCurrChannelList struct {
	RequestId        *int32 `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestBuddyCurrChannelList) Reset()         { *this = RequestBuddyCurrChannelList{} }
func (this *RequestBuddyCurrChannelList) String() string { return proto.CompactTextString(this) }
func (*RequestBuddyCurrChannelList) ProtoMessage()       {}

func (this *RequestBuddyCurrChannelList) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type RequestSyncBuddy struct {
	RequestId        *int32 `protobuf:"varint,1,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequestSyncBuddy) Reset()         { *this = RequestSyncBuddy{} }
func (this *RequestSyncBuddy) String() string { return proto.CompactTextString(this) }
func (*RequestSyncBuddy) ProtoMessage()       {}

func (this *RequestSyncBuddy) GetRequestId() int32 {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return 0
}

type MobileFeatureAction struct {
	Action           *string  `protobuf:"bytes,1,req" json:"Action,omitempty"`
	Latitude         *float32 `protobuf:"fixed32,2,opt" json:"Latitude,omitempty"`
	Longitude        *float32 `protobuf:"fixed32,3,opt" json:"Longitude,omitempty"`
	Param            []byte   `protobuf:"bytes,4,opt" json:"Param,omitempty"`
	RequestId        *string  `protobuf:"bytes,5,opt" json:"RequestId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *MobileFeatureAction) Reset()         { *this = MobileFeatureAction{} }
func (this *MobileFeatureAction) String() string { return proto.CompactTextString(this) }
func (*MobileFeatureAction) ProtoMessage()       {}

func (this *MobileFeatureAction) GetAction() string {
	if this != nil && this.Action != nil {
		return *this.Action
	}
	return ""
}

func (this *MobileFeatureAction) GetLatitude() float32 {
	if this != nil && this.Latitude != nil {
		return *this.Latitude
	}
	return 0
}

func (this *MobileFeatureAction) GetLongitude() float32 {
	if this != nil && this.Longitude != nil {
		return *this.Longitude
	}
	return 0
}

func (this *MobileFeatureAction) GetParam() []byte {
	if this != nil {
		return this.Param
	}
	return nil
}

func (this *MobileFeatureAction) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

type MobileClearAction struct {
	Location         *bool  `protobuf:"varint,1,opt" json:"Location,omitempty"`
	LoginType        *bool  `protobuf:"varint,2,opt" json:"LoginType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *MobileClearAction) Reset()         { *this = MobileClearAction{} }
func (this *MobileClearAction) String() string { return proto.CompactTextString(this) }
func (*MobileClearAction) ProtoMessage()       {}

func (this *MobileClearAction) GetLocation() bool {
	if this != nil && this.Location != nil {
		return *this.Location
	}
	return false
}

func (this *MobileClearAction) GetLoginType() bool {
	if this != nil && this.LoginType != nil {
		return *this.LoginType
	}
	return false
}

func init() {
}
